-- 机构表
CREATE TABLE IF NOT EXISTS sys_org (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    code VARCHAR(128) NOT NULL UNIQUE,
    type VARCHAR(32) NOT NULL,
    type_name VARCHAR(64),
    status VARCHAR(16) DEFAULT 'active',
    parent_id VARCHAR(128) DEFAULT 'root',
    order_num INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 监管系统配置表
CREATE TABLE IF NOT EXISTS sys_system (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    protocol VARCHAR(32),
    client_id VARCHAR(128),
    callback_url VARCHAR(256),
    algorithm VARCHAR(64),
    network VARCHAR(32),
    status VARCHAR(16) DEFAULT 'active',
    icon VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
