CREATE OR REPLACE PROCEDURE pm_rsdata.proc_cbrc_car_idx2_table(II_DATADATE IN STRING  --跑批日期
                                              )
/******************************
  @author:ZY
  @create-date:20240423
  @description:资本充足率取数表
  @modification history:
  m0.author-create_date-description
  
目标表：PM_RSDATA.CBRC_A_REPT_ITEM_VAL
临时表：PM_RSDATA.CBRC_PB_REPORT_DATA_CHANGE
     PM_RSDATA.CBRC_PB_REPORT_DATA_TMP
     PM_RSDATA.CBRC_PB_REPORT_DATA_INFO
配置表：PM_RSDATA.CBRC_INDEX_POSITION
集市表：PM_RSDATA.SMTMODS_M_GL_REPORT_DATA_STRG
     PM_RSDATA.CBRC_PB_REPORT_DATA

  
  *******************************/
 IS
 
  V_PROCEDURE VARCHAR(30); --当前储存过程名称
  V_TAB_NAME  VARCHAR(30); --目标表名
  I_DATADATE  STRING; --数据日期(数值型)YYYYMMDD
  V_DATADATE  VARCHAR(10); --数据日期(字符型)YYYY-MM-DD
  V_STEP_ID   INTEGER; --任务号
  V_ERRORCODE VARCHAR(20); --错误编码
  V_STEP_DESC VARCHAR(300); --任务描述
  V_STEP_FLAG INTEGER; --任务执行状态标识
  V_ERRORDESC VARCHAR(280); --错误内容
  II_STATUS   INTEGER DEFAULT 0; --断点续跑时，用于识别存储过程的是否跳过1--跳过 0--不跳过
  V_SYSTEM    VARCHAR(30);
  
BEGIN
  IF II_STATUS = 0 THEN
    V_STEP_ID   := 0;
    V_STEP_FLAG := 0;
    V_STEP_DESC := '参数初始化处理';
    V_DATADATE  :=TO_CHAR(DATE(I_DATADATE, 'YYYYMMDD'), 'YYYYMMDD');
    I_DATADATE  := II_DATADATE;
	V_SYSTEM    := 'CBRC';
    V_PROCEDURE := UPPER('PROC_CBRC_CAR_IDX2_TABLE');
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

    V_TAB_NAME := 'PM_RSDATA.CBRC_A_REPT_ITEM_VAL';
    
    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

    V_STEP_ID   := 1;
    V_STEP_FLAG := 0;
    V_STEP_DESC := '清理 [' || V_TAB_NAME || ']CAR表当期数据';
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

IF  SUBSTR(I_DATADATE,5,4) IN ('0331','0630','0930','1231')
  THEN
    DELETE FROM PM_RSDATA.CBRC_PB_REPORT_DATA_CHANGE T
     WHERE T.DATA_DATE = V_DATADATE
       AND T.ITEM_NAME IN('G4B-3(b)','G4B-5(a)');
    COMMIT;

    DELETE FROM PM_RSDATA.CBRC_A_REPT_ITEM_VAL T
     WHERE T.DATA_DATE = I_DATADATE
       AND SYS_NAM = 'CAR'
       AND T.REP_NUM  in ('G4B02X1','L1_G4C_1e','G4D00X1','L1_G4C_1_a','G4000X1','G4B01X1','G4B_1','G4B03X1','G4C01X1','G4B05X1','G4A01aX1','G4A00X1','L1_G4C_1b','L1_G4C_1d','L1_G4A_2')
       AND T.FLAG = '2';
    COMMIT;
ELSE
  DELETE FROM PM_RSDATA.CBRC_A_REPT_ITEM_VAL T
     WHERE T.DATA_DATE = I_DATADATE
       AND SYS_NAM = 'CAR'
       AND T.REP_NUM  in ('G4B02X1')
       AND T.FLAG = '2';
    COMMIT;
END IF ;

 EXECUTE IMMEDIATE 'TRUNCATE TABLE PM_RSDATA.CBRC_PB_REPORT_DATA_TMP';

 EXECUTE IMMEDIATE 'TRUNCATE TABLE PM_RSDATA.CBRC_PB_REPORT_DATA_INFO';



    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

  --=====================================
    -- 资本充足率表列转行---
    --=====================================


    V_STEP_ID   := 2;
    V_STEP_DESC := '资本充足率表列转行';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);


INSERT INTO PM_RSDATA.CBRC_PB_REPORT_DATA_INFO
(
DATA_ID,
       ITEM_CD,
       ITEM_NAME,
       LINE_NUMBER,
       ITEM_A,
       ITEM_B,
       LOAD_DATE,
       DATA_DATE,
       SOLO_NO,
       ORG_CD,
       CCY_CD,
       VERSION,
       VERSION_STATUS,
       OPERATE_DT,
       OPERATE_ID,
       OPERATE_NAME,
       BUSINESS_LINE_CD,
       ACCORG_PARTENT_NO,
       GROUP_CD,
       ITEM_NUM,
       ITEM_VAL

)
SELECT  DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD, ITEM_NUM, ITEM_VAL
 FROM (
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_C'  AS ITEM_NUM, ITEM_C   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_D'  AS ITEM_NUM, ITEM_D   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_E'  AS ITEM_NUM, ITEM_E   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_F'  AS ITEM_NUM, ITEM_F   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_G'  AS ITEM_NUM, ITEM_G   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_H'  AS ITEM_NUM, ITEM_H   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_I'  AS ITEM_NUM, ITEM_I   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_J'  AS ITEM_NUM, ITEM_J   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_K'  AS ITEM_NUM, ITEM_K   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_L'  AS ITEM_NUM, ITEM_L   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_M'  AS ITEM_NUM, ITEM_M   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_N'  AS ITEM_NUM, ITEM_N   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_O'  AS ITEM_NUM, ITEM_O   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_P'  AS ITEM_NUM, ITEM_P   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_Q'  AS ITEM_NUM, ITEM_Q   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_R'  AS ITEM_NUM, ITEM_R   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_S'  AS ITEM_NUM, ITEM_S   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_T'  AS ITEM_NUM, ITEM_T   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_U'  AS ITEM_NUM, ITEM_U   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_V'  AS ITEM_NUM, ITEM_V   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_W'  AS ITEM_NUM, ITEM_W   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_X'  AS ITEM_NUM, ITEM_X   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_Y'  AS ITEM_NUM, ITEM_Y   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_Z'  AS ITEM_NUM, ITEM_Z   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AA'  AS ITEM_NUM,  ITEM_AA   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AB'  AS ITEM_NUM,  ITEM_AB   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AC'  AS ITEM_NUM,  ITEM_AC   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AD'  AS ITEM_NUM,  ITEM_AD   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AE'  AS ITEM_NUM,  ITEM_AE   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AF'  AS ITEM_NUM,  ITEM_AF   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AG'  AS ITEM_NUM,  ITEM_AG   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AH'  AS ITEM_NUM,  ITEM_AH   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AI'  AS ITEM_NUM,  ITEM_AI   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AJ'  AS ITEM_NUM,  ITEM_AJ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AK'  AS ITEM_NUM,  ITEM_AK   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AL'  AS ITEM_NUM,  ITEM_AL   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AM'  AS ITEM_NUM,  ITEM_AM   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AN'  AS ITEM_NUM,  ITEM_AN   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AO'  AS ITEM_NUM,  ITEM_AO   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AP'  AS ITEM_NUM,  ITEM_AP   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AQ'  AS ITEM_NUM,  ITEM_AQ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AR'  AS ITEM_NUM,  ITEM_AR   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AS'  AS ITEM_NUM,  ITEM_AS   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AT'  AS ITEM_NUM,  ITEM_AT   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AU'  AS ITEM_NUM,  ITEM_AU   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AV'  AS ITEM_NUM,  ITEM_AV   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AW'  AS ITEM_NUM,  ITEM_AW   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AX'  AS ITEM_NUM,  ITEM_AX   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AY'  AS ITEM_NUM,  ITEM_AY   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_AZ'  AS ITEM_NUM,  ITEM_AZ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BA'  AS ITEM_NUM,  ITEM_BA   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BB'  AS ITEM_NUM,  ITEM_BB   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BC'  AS ITEM_NUM,  ITEM_BC   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BD'  AS ITEM_NUM,  ITEM_BD   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BE'  AS ITEM_NUM,  ITEM_BE   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BF'  AS ITEM_NUM,  ITEM_BF   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BG'  AS ITEM_NUM,  ITEM_BG   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BH'  AS ITEM_NUM,  ITEM_BH   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BI'  AS ITEM_NUM,  ITEM_BI   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BJ'  AS ITEM_NUM,  ITEM_BJ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BK'  AS ITEM_NUM,  ITEM_BK   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BL'  AS ITEM_NUM,  ITEM_BL   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BM'  AS ITEM_NUM,  ITEM_BM   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BN'  AS ITEM_NUM,  ITEM_BN   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BO'  AS ITEM_NUM,  ITEM_BO   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BP'  AS ITEM_NUM,  ITEM_BP   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BQ'  AS ITEM_NUM,  ITEM_BQ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BR'  AS ITEM_NUM,  ITEM_BR   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BS'  AS ITEM_NUM,  ITEM_BS   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BT'  AS ITEM_NUM,  ITEM_BT   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BU'  AS ITEM_NUM,  ITEM_BU   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BV'  AS ITEM_NUM,  ITEM_BV   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BW'  AS ITEM_NUM,  ITEM_BW   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BX'  AS ITEM_NUM,  ITEM_BX   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BY'  AS ITEM_NUM,  ITEM_BY   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_BZ'  AS ITEM_NUM,  ITEM_BZ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CA'  AS ITEM_NUM,  ITEM_CA   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CB'  AS ITEM_NUM,  ITEM_CB   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CC'  AS ITEM_NUM,  ITEM_CC   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CCD'  AS ITEM_NUM, ITEM_CCD   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CE'  AS ITEM_NUM,  ITEM_CE   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CF'  AS ITEM_NUM,  ITEM_CF   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CG'  AS ITEM_NUM,  ITEM_CG   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CH'  AS ITEM_NUM,  ITEM_CH   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CI'  AS ITEM_NUM,  ITEM_CI   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CJ'  AS ITEM_NUM,  ITEM_CJ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CK'  AS ITEM_NUM,  ITEM_CK   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CL'  AS ITEM_NUM,  ITEM_CL   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CM'  AS ITEM_NUM,  ITEM_CM   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CN'  AS ITEM_NUM,  ITEM_CN   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CO'  AS ITEM_NUM,  ITEM_CO   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CP'  AS ITEM_NUM,  ITEM_CP   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CQ'  AS ITEM_NUM,  ITEM_CQ   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CR'  AS ITEM_NUM,  ITEM_CR   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CS'  AS ITEM_NUM,  ITEM_CS   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CT'  AS ITEM_NUM,  ITEM_CT   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CU'  AS ITEM_NUM,  ITEM_CU   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CV'  AS ITEM_NUM,  ITEM_CV   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CW'  AS ITEM_NUM,  ITEM_CW   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CX'  AS ITEM_NUM,  ITEM_CX   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CY'  AS ITEM_NUM,  ITEM_CY   AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
UNION  ALL
SELECT DATA_ID,ITEM_CD,ITEM_NAME,LINE_NUMBER,ITEM_A,ITEM_B,LOAD_DATE,DATA_DATE,SOLO_NO,ORG_CD,CCY_CD,VERSION,VERSION_STATUS,OPERATE_DT,OPERATE_ID,OPERATE_NAME,BUSINESS_LINE_CD,ACCORG_PARTENT_NO,GROUP_CD,'ITEM_CZ' AS ITEM_NUM,  ITEM_CZ  AS  ITEM_VAL  FROM PM_RSDATA.CBRC_PB_REPORT_DATA
) T 
WHERE DATA_DATE =I_DATADATE;
COMMIT;


INSERT INTO    PM_RSDATA.CBRC_PB_REPORT_DATA_TMP
(DATA_ID,
ITEM_CD,
ITEM_NAME,
ITEM_NAME_ZH,
LINE_NUMBER,
ITEM_A,
ITEM_B,
LOAD_DATE,
DATA_DATE,
SOLO_NO,
ORG_CD,
CCY_CD,
VERSION,
VERSION_STATUS,
OPERATE_DT,
OPERATE_ID,
OPERATE_NAME,
BUSINESS_LINE_CD,
ACCORG_PARTENT_NO,
GROUP_CD,
ITEM_NUM,
ITEM_NUM_ZH,
ITEM_VAL)
SELECT 
DATA_ID,
ITEM_CD,
ITEM_NAME,
CASE  WHEN  ITEM_NAME = 'G4C-1(e)' THEN  'L1_G4C_1e'
      WHEN  ITEM_NAME = 'G4D' THEN  'G4D00X1'
      WHEN  ITEM_NAME = 'G4B-2' THEN  'G4B02X1'
      WHEN  ITEM_NAME = 'G4C-1(a)' THEN  'L1_G4C_1_a'
      WHEN  ITEM_NAME = 'G40' THEN  'G4000X1'
      WHEN  ITEM_NAME = 'G4B-3' THEN  'G4B03X1'
      WHEN  ITEM_NAME = 'G4B-1' THEN  'G4B01X1'
      WHEN  ITEM_NAME = 'G4B-1_II' THEN  'G4B01X1'
      WHEN  ITEM_NAME = 'G4C-1' THEN  'G4C01X1'
      WHEN  ITEM_NAME = 'G4B-5' THEN  'G4B05X1'
      WHEN  ITEM_NAME = 'G4A-1(a)' THEN  'G4A01aX1'
      WHEN  ITEM_NAME = 'G4A' THEN  'G4A00X1'
      WHEN  ITEM_NAME = 'G4C-1(b)' THEN  'L1_G4C_1b'
      WHEN  ITEM_NAME = 'G4C-1(d)' THEN  'L1_G4C_1d'
      WHEN  ITEM_NAME = 'G4A-2' THEN  'L1_G4A_2'
      END  AS ITEM_NAME_ZH ,
`LINE_NUMBER`,
ITEM_A,
ITEM_B,
LOAD_DATE,
DATA_DATE,
SOLO_NO,
CASE WHEN ( ORG_CD ='001' OR SOLO_NO ='001')  THEN '990000' ELSE  ORG_CD  END  AS  ORG_CD,
CCY_CD,
VERSION,
VERSION_STATUS,
OPERATE_DT,
OPERATE_ID,
OPERATE_NAME,
BUSINESS_LINE_CD,
ACCORG_PARTENT_NO,
GROUP_CD,
ITEM_NUM,
DECODE (ITEM_NUM,'ITEM_C','3',
'ITEM_D','4',
'ITEM_E','5',
'ITEM_F','6',
'ITEM_G','7',
'ITEM_H','8',
'ITEM_I','9',
'ITEM_J','10',
'ITEM_K','11',
'ITEM_L','12',
'ITEM_M','13',
'ITEM_N','14',
'ITEM_O','15',
'ITEM_P','16',
'ITEM_Q','17',
'ITEM_R','18',
'ITEM_S','19',
'ITEM_T','20',
'ITEM_U','21',
'ITEM_V','22',
'ITEM_W','23',
'ITEM_X','24',
'ITEM_Y','25',
'ITEM_Z','26',
'ITEM_AA','27',
'ITEM_AB','28',
'ITEM_AC','29',
'ITEM_AD','30',
'ITEM_AE','31',
'ITEM_AF','32',
'ITEM_AG','33',
'ITEM_AH','34',
'ITEM_AI','35',
'ITEM_AJ','36',
'ITEM_AK','37',
'ITEM_AL','38',
'ITEM_AM','39',
'ITEM_AN','40',
'ITEM_AO','41',
'ITEM_AP','42',
'ITEM_AQ','43',
'ITEM_AR','44',
'ITEM_AS','45',
'ITEM_AT','46',
'ITEM_AU','47',
'ITEM_AV','48',
'ITEM_AW','49',
'ITEM_AX','50',
'ITEM_AY','51',
'ITEM_AZ','52',
'ITEM_BA','53',
'ITEM_BB','54',
'ITEM_BC','55',
'ITEM_BD','56',
'ITEM_BE','57',
'ITEM_BF','58',
'ITEM_BG','59',
'ITEM_BH','60',
'ITEM_BI','61',
'ITEM_BJ','62',
'ITEM_BK','63',
'ITEM_BL','64',
'ITEM_BM','65',
'ITEM_BN','66',
'ITEM_BO','67',
'ITEM_BP','68',
'ITEM_BQ','69',
'ITEM_BR','70',
'ITEM_BS','71',
'ITEM_BT','72',
'ITEM_BU','73',
'ITEM_BV','74',
'ITEM_BW','75',
'ITEM_BX','76',
'ITEM_BY','77',
'ITEM_BZ','78',
'ITEM_CA','79',
'ITEM_CB','80',
'ITEM_CC','81',
'ITEM_CCD','82',
'ITEM_CE','83',
'ITEM_CF','84',
'ITEM_CG','85',
'ITEM_CH','86',
'ITEM_CI','87',
'ITEM_CJ','88',
'ITEM_CK','89',
'ITEM_CL','90',
'ITEM_CM','91',
'ITEM_CN','92',
'ITEM_CO','93',
'ITEM_CP','94',
'ITEM_CQ','95',
'ITEM_CR','96',
'ITEM_CS','97',
'ITEM_CT','98',
'ITEM_CU','99',
'ITEM_CV','100',
'ITEM_CW','101',
'ITEM_CX','102',
'ITEM_CY','103',
'ITEM_CZ','104')  AS ITEM_NUM_ZH,
ITEM_VAL * 10000 FROM  PM_RSDATA.CBRC_PB_REPORT_DATA_INFO T ;
 COMMIT;

V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

    --=====================================
    --   资本充足率G4B-1(G4B01X1)取数
    --=====================================

    V_STEP_ID   := 3;
    V_STEP_DESC := '资本充足率G4B-1(G4B01X1)取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

IF SUBSTR(I_DATADATE,5,4) IN ('0331','0630','0930','1231')
  THEN

INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM  PM_RSDATA.CBRC_PB_REPORT_DATA_TMP TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER-2) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4B-1','G4B-1_II') ;
COMMIT;


    DELETE FROM PM_RSDATA.CBRC_A_REPT_ITEM_VAL T WHERE T.DATA_DATE = I_DATADATE AND T.ORG_NUM = '009816' AND T.SYS_NAM = 'CAR'
      AND T.REP_NUM IN ('G4B01X1','G4B_1')
      AND T.ITEM_NUM IN ('L1_G4B_1_19.1.A.2024','G4B_1_1_11.1.A','L1_G4B_1_19.3.10.A.2024','G4B_1_1_11.4.6.A') ;
    COMMIT;

--JLBA202409260002_关于1104系统完善表外理财业务报表的相关需求
    INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
    (DATA_DATE,ORG_NUM,SYS_NAM,REP_NUM,ITEM_NUM,ITEM_VAL,ITEM_VAL_V,FLAG,B_CURR_CD,IS_TOTAL)
    SELECT I_DATADATE,T.BIZ_ORG,'CAR','G4B01X1','L1_G4B_1_19.1.A.2024',SUM(T.DATA_ITEM_VAL),'','2','','N'
      FROM PM_RSDATA.SMTMODS_M_GL_REPORT_DATA_STRG T
     WHERE T.SYS = '99'
       AND T.ACCT_DT = I_DATADATE
       AND T.CURR_CD = 'CCC' --本外币合计
       AND T.FREQ = 'D'
       AND T.BIZ_ORG = '009816'
       AND T.REPORT_CD IN ('000001')
       AND T.DATA_ITEM_CD = '000001^D^32' --其他资产
    GROUP BY T.BIZ_ORG
    ;
    COMMIT;

    INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
    (DATA_DATE,ORG_NUM,SYS_NAM,REP_NUM,ITEM_NUM,ITEM_VAL,ITEM_VAL_V,FLAG,B_CURR_CD,IS_TOTAL)
    SELECT I_DATADATE,T.BIZ_ORG,'CAR','G4B_1','G4B_1_1_11.1.A',SUM(T.DATA_ITEM_VAL),'','2','','N'
      FROM PM_RSDATA.SMTMODS_M_GL_REPORT_DATA_STRG T
     WHERE T.SYS = '99'
       AND T.ACCT_DT = I_DATADATE
       AND T.CURR_CD = 'CCC' --本外币合计
       AND T.FREQ = 'D'
       AND T.BIZ_ORG = '009816'
       AND T.REPORT_CD IN ('000001')
       AND T.DATA_ITEM_CD = '000001^D^32' --其他资产
     GROUP BY T.BIZ_ORG
    ;
    COMMIT;

    INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
    (DATA_DATE,ORG_NUM,SYS_NAM,REP_NUM,ITEM_NUM,ITEM_VAL,ITEM_VAL_V,FLAG,B_CURR_CD,IS_TOTAL)
    SELECT I_DATADATE,T.BIZ_ORG,'CAR','G4B01X1','L1_G4B_1_19.3.10.A.2024',SUM(T.DATA_ITEM_VAL),'','2','','N'
      FROM PM_RSDATA.SMTMODS_M_GL_REPORT_DATA_STRG T
     WHERE T.SYS = '99'
       AND T.ACCT_DT = I_DATADATE
       AND T.CURR_CD = 'CCC' --本外币合计
       AND T.FREQ = 'D'
       AND T.BIZ_ORG = '009816'
       AND T.REPORT_CD IN ('000001')
       AND T.DATA_ITEM_CD = '000001^D^15' --其他应收款
    GROUP BY T.BIZ_ORG
    ;
    COMMIT;

    INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
    (DATA_DATE,ORG_NUM,SYS_NAM,REP_NUM,ITEM_NUM,ITEM_VAL,ITEM_VAL_V,FLAG,B_CURR_CD,IS_TOTAL)
    SELECT I_DATADATE,T.BIZ_ORG,'CAR','G4B_1','G4B_1_1_11.4.6.A',SUM(T.DATA_ITEM_VAL),'','2','','N'
      FROM PM_RSDATA.SMTMODS_M_GL_REPORT_DATA_STRG T
     WHERE T.SYS = '99'
       AND T.ACCT_DT = I_DATADATE
       AND T.CURR_CD = 'CCC' --本外币合计
       AND T.FREQ = 'D'
       AND T.BIZ_ORG = '009816'
       AND T.REPORT_CD IN ('000001')
       AND T.DATA_ITEM_CD = '000001^D^15' --其他应收款
     GROUP BY T.BIZ_ORG
    ;
    COMMIT;

    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

    --=====================================
    --   资本充足率G4B-2(G4B02X1)和G4B-5(G4B05X1)取数
    --=====================================

    V_STEP_ID   := 4;
    V_STEP_DESC := '资本充足率G4B-2(G4B02X1)和G4B-5(G4B05X1)取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM PM_RSDATA.CBRC_PB_REPORT_DATA_TMP   TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER-1) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4B-2');
   COMMIT;

    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);



INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM (select DATA_DATE,
       ORG_CD,
       CCY_CD,
       ITEM_NAME_ZH,
       CASE WHEN  ITEM_NAME_ZH ='G4B05X1'  AND   LINE_NUMBER = '1006' THEN  30
         ELSE  LINE_NUMBER  END  LINE_NUMBER,
       ITEM_NUM_ZH,
       ITEM_NAME,
       ITEM_VAL
  from PM_RSDATA.CBRC_PB_REPORT_DATA_TMP )  TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER-1) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4B-5');
   COMMIT;


    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);



    --=====================================
    --   资本充足率G4B-3,G4C-1(a),G4C-1(b),G4A,G4A-1(a)取数
    --=====================================

    V_STEP_ID   := 5;
    V_STEP_DESC := 'G4B-3,G4C-1(a),G4C-1(b),G4A,G4A-1(a)取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

  INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM  (select DATA_DATE,
       ORG_CD,
       CCY_CD,
       ITEM_NAME_ZH,
       CASE  WHEN  ITEM_NAME_ZH ='G4A00X1'  AND   LINE_NUMBER = '95' THEN  91
         ELSE  LINE_NUMBER  END  LINE_NUMBER,
       ITEM_NUM_ZH,
       ITEM_NAME,
       ITEM_VAL
  from PM_RSDATA.CBRC_PB_REPORT_DATA_TMP ) TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4B-3','G4C-1(a)','G4C-1(b)','G4A','G4A-1(a)');
   COMMIT;


    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

   --=====================================
    --   资本充足率G4C-1(G4C01X1)和 G4C-1(d)(L1_G4C_1d)和G4C-1(e)(L1_G4C_1e)和G4A-2和G4D取数
    --=====================================

    V_STEP_ID   := 6;
    V_STEP_DESC := '资本充足率G4C-1(G4C01X1)和 G4C-1(d)(L1_G4C_1d)和G4C-1(e)(L1_G4C_1e)和G4D取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

  INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM  PM_RSDATA.CBRC_PB_REPORT_DATA_TMP  TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4C-1','G4C-1(d)','G4C-1(e)','G4A-2','G4D');
    COMMIT;

    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);


    --=====================================
    --   资本充足率G40(G4000X1)取数
    --=====================================

    V_STEP_ID   := 7;
    V_STEP_DESC := '资本充足率G40(G4000X1)取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM PM_RSDATA.CBRC_PB_REPORT_DATA_TMP   TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER-1) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G40');
   COMMIT;


    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);




    --==========================================================
    --   资本充足率G4B-3（b）（L1_G4B_3b_I、L1_G4B_3b_II_1、L1_G4B_3b_II_2）和G4B-5(a)(L1_G4B_5a)变长表取数
    --===========================================================
    
    V_STEP_ID   := 8;
    V_STEP_DESC := '资本充足率G4B-3（b）（L1_G4B_3b_I、L1_G4B_3b_II_1、L1_G4B_3b_II_2）和G4B-5(a)(L1_G4B_5a)变长表取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

   INSERT INTO  PM_RSDATA.CBRC_PB_REPORT_DATA_CHANGE
(data_id,
LINE_NUMBER,
item_name,
item_a,
item_b,
item_c,
item_d,
item_e,
item_f,
item_g,
item_h,
item_i,
item_j,
item_k,
item_l,
item_m,
item_n,
item_o,
item_p,
item_q,
item_r,
item_s,
item_t,
item_u,
item_v,
item_w,
item_x,
item_y,
item_z,
item_aa,
item_ab,
item_ac,
item_ad,
item_ae,
item_af,
data_date,
item_ag,
item_ah,
item_ai,
item_aj,
item_ak,
item_al,
item_am,
item_an,
item_ao,
item_ap,
item_aq,
item_ar,
item_as,
item_at,
item_au,
item_av,
item_aw,
item_ax,
item_ay,
item_az,
item_ba,
item_bb,
item_bc,
item_bd,
item_be,
item_bf,
item_bg,
item_bh,
item_bi,
item_bj,
item_bk,
item_bl,
item_bm,
item_bn,
item_bo,
item_bp,
item_bq,
item_br,
item_bs,
item_bt,
item_bu,
item_bv,
item_bw,
item_bx,
item_by,
item_bz,
item_ca,
item_cb,
item_cc,
item_ccd,
item_ce,
item_cf,
item_cg,
item_ch,
item_ci,
item_cj,
item_ck,
item_cl,
item_cm,
item_cn,
item_co,
item_cp,
item_cq,
item_cr,
item_cs,
item_ct,
item_cu,
item_cv,
item_cw,
item_cx,
item_cy,
item_cz,
org_cd,
ccy_cd
)
select 
data_id,
LINE_NUMBER,
item_name,
item_a,
item_b,
item_c,
item_d,
item_e,
item_f,
item_g,
item_h,
item_i,
item_j,
item_k,
item_l,
item_m,
item_n,
item_o,
item_p,
item_q,
item_r,
item_s,
item_t,
item_u,
item_v,
item_w,
item_x,
item_y,
item_z,
item_aa,
item_ab,
item_ac,
item_ad,
item_ae,
item_af,
substr(data_date,1,4)||'-'||substr(data_date,5,2)||'-'||substr(data_date,7,2) data_date ,
item_ag,
item_ah,
item_ai,
item_aj,
item_ak,
item_al,
item_am,
item_an,
item_ao,
item_ap,
item_aq,
item_ar,
item_as,
item_at,
item_au,
item_av,
item_aw,
item_ax,
item_ay,
item_az,
item_ba,
item_bb,
item_bc,
item_bd,
item_be,
item_bf,
item_bg,
item_bh,
item_bi,
item_bj,
item_bk,
item_bl,
item_bm,
item_bn,
item_bo,
item_bp,
item_bq,
item_br,
item_bs,
item_bt,
item_bu,
item_bv,
item_bw,
item_bx,
item_by,
item_bz,
item_ca,
item_cb,
item_cc,
item_ccd,
item_ce,
item_cf,
item_cg,
item_ch,
item_ci,
item_cj,
item_ck,
item_cl,
item_cm,
item_cn,
item_co,
item_cp,
item_cq,
item_cr,
item_cs,
item_ct,
item_cu,
item_cv,
item_cw,
item_cx,
item_cy,
item_cz,
CASE WHEN ( ORG_CD ='001' OR SOLO_NO ='001')  THEN '990000' ELSE  ORG_CD  END  AS  ORG_CD ,
ccy_cd
from PM_RSDATA.CBRC_PB_REPORT_DATA T
WHERE  T.ITEM_NAME IN('G4B-3(b)','G4B-5(a)')
and T.DATA_DATE =I_DATADATE;
COMMIT;

  

    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

ELSE
      --=====================================
    --   资本充足率G4B-2(G4B02X1)排除季报日期取数
    --   20240425 暂时有月报的取数逻辑，但是按照季报报送，防止1年后旧的报表取消，新的这个表变成月报
    --调度平台每季度1号跑批。
    --=====================================

    V_STEP_ID   := 9;
    V_STEP_DESC := '资本充足率G4B-2(G4B02X1)排除季报日期取数';
    V_STEP_FLAG := 0;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

INSERT INTO PM_RSDATA.CBRC_A_REPT_ITEM_VAL
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,B_CURR_CD,IS_TOTAL)
SELECT 
TMP.DATA_DATE,
TMP.ORG_CD,
'CAR',
TMP1.REPORT_ID,
TMP1.INDEX_ID,
TMP.ITEM_VAL,
'2',
TMP.CCY_CD,
'N'
  FROM PM_RSDATA.CBRC_PB_REPORT_DATA_TMP   TMP
 INNER join (
             SELECT T.ID,
                     T.INDEX_ID,
                     T.REPORT_ID,
                     T.REPORT_CALIBRE_ID,
                     TO_CHAR(T.ROW_NUM) ROW_NUM,
                     TO_CHAR(T.COL_NUM) COL_NUM
               FROM PM_RSDATA.CBRC_INDEX_POSITION T
              INNER JOIN (SELECT MIN(REPORT_CALIBRE_ID) CALIBRE_ID, REPORT_ID
                            FROM PM_RSDATA.CBRC_INDEX_POSITION
                           GROUP BY REPORT_ID) T1
                 ON T.REPORT_CALIBRE_ID = T1.CALIBRE_ID
                AND T.REPORT_ID = T1.REPORT_ID
             ) TMP1
    ON TMP.ITEM_NAME_ZH = TMP1.REPORT_ID
   AND (TMP.LINE_NUMBER-1) = TMP1.ROW_NUM
   AND TMP.ITEM_NUM_ZH = TMP1.COL_NUM
 WHERE TMP.DATA_DATE = I_DATADATE
  AND TMP.ITEM_NAME in ('G4B-2');
   COMMIT;


    V_STEP_FLAG := 1;
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);


  END IF ;

--===========================================================================
    V_STEP_FLAG := 1;
    V_STEP_DESC := V_PROCEDURE || '的业务逻辑全部处理完成';
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);

      COMMIT;
	  
    DBMS_OUTPUT.PUT_LINE('O_STATUS=0');
    DBMS_OUTPUT.PUT_LINE('O_STATUS_DEC=完成'); 
    ------------------------------------------------------------------

  END IF;

EXCEPTION
  WHEN OTHERS THEN
    V_ERRORCODE := SQLCODE;
    V_ERRORDESC := SUBSTR(SQLERRM, 1, 280);
    V_STEP_DESC := '发生异常。详细信息为，' || TO_CHAR(SQLCODE) ||
                   SUBSTR(SQLERRM, 1, 280);
				   
    DBMS_OUTPUT.PUT_LINE('O_STATUS=-1');
    DBMS_OUTPUT.PUT_LINE('O_STATUS_DEC=失败'); 
    --记录异常信息
    SP_RSBP_ETL_LOG(V_SYSTEM,V_PROCEDURE,
                V_STEP_ID,
                V_ERRORCODE,
                V_STEP_DESC,
                II_DATADATE);
     ROLLBACK;
   
END proc_cbrc_car_idx2_table;
