-- ============================================================
-- 文件名: S26_II城商行省外分支机构情况表.sql
-- 生成时间: 2025-12-18 13:53:40
-- 说明: 采用 CTE (WITH) 聚合去重模式生成，大幅减小血缘解析压力
-- ============================================================

-- 指标: S26_II_6.T.2024
INSERT INTO `S26_II_6.T.2024`
  (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
  SELECT 
   T.DATA_DATE,
   T.ORG_NUM,
   'CBRC',
   'S26_II',
   'S26_II_6.T.2024',
   COUNT(1) AS ITEM_VAL,
   '2'
    FROM CBRC_TMP_LOAN_FEI_S2602 T
   WHERE DATA_DATE = I_DATADATE
   GROUP BY T.DATA_DATE, T.ORG_NUM;


-- 指标: S26_II_7.M.2024
INSERT INTO `S26_II_7.M.2024`
(DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT 
 A.DATA_DATE,
 A.ORG_NUM,
 'CBRC' AS SYS_NAM,
 'S26_II' AS REP_NUM,
 'S26_II_7.M.2024' AS ITEM_NUM,
 SUM(A.LOAN_ACCT_BAL * U.CCY_RATE) AS ITEM_VAL,
 '2' AS FLAG
  FROM SMTMODS_L_ACCT_LOAN A
  LEFT JOIN SMTMODS_L_PUBL_RATE U
    ON U.CCY_DATE = I_DATADATE
   AND U.BASIC_CCY = A.CURR_CD --基准币种
   AND U.FORWARD_CCY = 'CNY' --折算币种
   AND U.DATA_DATE = I_DATADATE
 WHERE A.DATA_DATE = I_DATADATE
   AND NOT EXISTS (SELECT 
         1
          FROM CBRC_TMP_LOAN_S2602 T2
         WHERE A.DATA_DATE = T2.DATA_DATE
           AND A.LOAN_NUM = T2.LOAN_NUM)
   AND A.ACCT_TYP NOT LIKE '90%' --去委托贷款
   AND A.ACCT_STS <> '3' --去结清
   AND A.CANCEL_FLG <> 'Y' --去核销
   AND A.LOAN_STOCKEN_DATE IS NULL    --add by haorui 20250311 JLBA202408200012 资产未转让
 GROUP BY A.DATA_DATE, A.ORG_NUM;


-- 指标: S26_II_6.S.2024
INSERT INTO `S26_II_6.S.2024`
  (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
    SELECT 
     T.DATA_DATE,
     T.ORG_NUM,
     'CBRC',
     'S26_II',
     'S26_II_6.S.2024',
     SUM(T.LOAN_ACCT_BAL) AS ITEM_VAL,
     '2'
      FROM CBRC_TMP_LOAN_FEI_S2602 T
     WHERE DATA_DATE = I_DATADATE
     GROUP BY T.DATA_DATE, T.ORG_NUM;


-- 指标: S26_II_6.C.2024
INSERT INTO `S26_II_6.C.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
          SELECT 
      T.DATA_DATE,
      T.FIRST_ORG AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_II' AS REP_NUM,
      'S26_II_6.C.2024' AS ITEM_NUM,
      COUNT(DISTINCT T.SECOND_ORG) AS ITEM_VAL,
      '2'
       FROM CBRC_TMP_ORG_S2602 T
      WHERE T.DATA_DATE = I_DATADATE
      GROUP BY T.DATA_DATE, T.FIRST_ORG;


-- 指标: S26_II_6.D.2024
INSERT INTO `S26_II_6.D.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
 SELECT 
      T.DATA_DATE,
      T.FIRST_ORG AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_II' AS REP_NUM,
      'S26_II_6.D.2024' AS ITEM_NUM,
      COUNT(DISTINCT T.THIRD_ORG) AS ITEM_VAL,
      '2'
       FROM CBRC_TMP_ORG_S2602 T
      WHERE T.DATA_DATE = I_DATADATE
      GROUP BY T.DATA_DATE, T.FIRST_ORG;


-- 指标: S26_II_6.U.2024
INSERT INTO `S26_II_6.U.2024`
  (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG,IS_TOTAL)
    SELECT A.DATA_DATE,
         A.FIRST_ORG,
         'CBRC',
         'S26_II',
         'S26_II_6.U.2024',
         A.ITEM_VAL,
         '2',
         'N'
    FROM (SELECT 
           T.DATA_DATE,
           T1.FIRST_ORG,
           T.CUST_NO,
           T.TAG,
           SUM(LOAN_ACCT_BAL) AS ITEM_VAL,
           ROW_NUMBER() OVER(PARTITION BY T.DATA_DATE, T1.FIRST_ORG  ORDER BY SUM(LOAN_ACCT_BAL) DESC) AS RANK_SEQ
            FROM CBRC_TMP_LOAN_FEI_S2602 T
            LEFT  JOIN  CBRC_TMP_ORG_S2602 T1
            ON T.ORG_NUM   = T1.THIRD_ORG
            AND T.DATA_DATE  = T1.DATA_DATE
           WHERE T.DATA_DATE = I_DATADATE
           GROUP BY T.DATA_DATE,
           T.DATA_DATE,
           T1.FIRST_ORG,
           T.CUST_NO,
           T.TAG) A
   WHERE RANK_SEQ <= 10  AND A.FIRST_ORG IS NOT  NULL;


-- 指标: S26_II_6.A.2024
INSERT INTO `S26_II_6.A.2024`
  (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)

  SELECT 
   T.DATA_DATE,
   T.FIRST_ORG AS ORG_NUM,
   'CBRC' AS SYS_NAM,
   'S26_II' AS REP_NUM,
   'S26_II_6.A.2024' AS ITEM_NUM,
   COUNT(DISTINCT T.FIRST_ORG) AS ITEM_VAL,
   '2'
    FROM CBRC_TMP_ORG_S2602 T
   WHERE T.DATA_DATE = I_DATADATE
   GROUP BY  T.DATA_DATE,
   T.FIRST_ORG;


