-- ============================================================
-- 文件名: S26_I城商行省外经营情况统计表.sql
-- 生成时间: 2025-12-18 13:53:40
-- 说明: 采用 CTE (WITH) 聚合去重模式生成，大幅减小血缘解析压力
-- ============================================================

-- ========== 逻辑组 0: 共 32 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       C.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
           WHEN (C.REGION_CD LIKE '11%' AND C.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.C.2024'  --'%北京%'
           WHEN C.REGION_CD LIKE '12%' THEN 'S26_I_3_2.C.2024'  --'%天津%'
           WHEN C.REGION_CD LIKE '13%' THEN 'S26_I_3_3.C.2024'  --'%河北%'
           WHEN C.REGION_CD LIKE '14%' THEN 'S26_I_3_4.C.2024'  --'%山西%'
           WHEN C.REGION_CD LIKE '15%' THEN 'S26_I_3_5.C.2024'  --'%内蒙古
           WHEN C.REGION_CD LIKE '21%' THEN 'S26_I_3_6.C.2024'  --'%辽宁%'
           WHEN C.REGION_CD LIKE '22%' THEN 'S26_I_3_7.C.2024'  --'%吉林%'
           WHEN C.REGION_CD LIKE '23%' THEN 'S26_I_3_8.C.2024'  --'%黑龙江
           WHEN (C.REGION_CD LIKE '31%' OR C.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.C.2024'  --'%上海%'
           WHEN C.REGION_CD LIKE '32%' THEN 'S26_I_3_10.C.2024'  --'%江苏%'
           WHEN C.REGION_CD LIKE '33%' THEN 'S26_I_3_11.C.2024'  --'%浙江%'
           WHEN C.REGION_CD LIKE '34%' THEN 'S26_I_3_12.C.2024'  --'%安徽%'
           WHEN C.REGION_CD LIKE '35%' THEN 'S26_I_3_13.C.2024'  --'%福建%'
           WHEN C.REGION_CD LIKE '36%' THEN 'S26_I_3_14.C.2024'  --'%江西%'
           WHEN C.REGION_CD LIKE '37%' THEN 'S26_I_3_15.C.2024'  --'%山东%'
           WHEN C.REGION_CD LIKE '41%' THEN 'S26_I_3_16.C.2024'  --'%河南%'
           WHEN C.REGION_CD LIKE '42%' THEN 'S26_I_3_17.C.2024'  --'%湖北%'
           WHEN C.REGION_CD LIKE '43%' THEN 'S26_I_3_18.C.2024'  --'%湖南%'
           WHEN C.REGION_CD LIKE '44%' THEN 'S26_I_3_19.C.2024'  --'%广东%'
           WHEN C.REGION_CD LIKE '45%' THEN 'S26_I_3_20.C.2024'  --'%广西%'
           WHEN C.REGION_CD LIKE '46%' THEN 'S26_I_3_21.C.2024'  --'%海南%'
           WHEN C.REGION_CD LIKE '50%' THEN 'S26_I_3_22.C.2024'  --'%重庆%'
           WHEN C.REGION_CD LIKE '51%' THEN 'S26_I_3_23.C.2024'  --'%四川%'
           WHEN C.REGION_CD LIKE '52%' THEN 'S26_I_3_24.C.2024'  --'%贵州%'
           WHEN C.REGION_CD LIKE '53%' THEN 'S26_I_3_25.C.2024'  --'%云南%'
           WHEN C.REGION_CD LIKE '54%' THEN 'S26_I_3_26.C.2024'  --'%西藏%'
           WHEN C.REGION_CD LIKE '61%' THEN 'S26_I_3_27.C.2024'  --'%陕西%'
           WHEN C.REGION_CD LIKE '62%' THEN 'S26_I_3_28.C.2024'  --'%甘肃%'
           WHEN C.REGION_CD LIKE '63%' THEN 'S26_I_3_29.C.2024'  --'%青海%'
           WHEN C.REGION_CD LIKE '64%' THEN 'S26_I_3_30.C.2024'  --'%宁夏%'
           WHEN C.REGION_CD LIKE '65%' THEN 'S26_I_3_31.C.2024'  --'%新疆%'
           WHEN SUBSTR(C.REGION_CD,1,2) IN ('71','81','82') THEN 'S26_I_3_32.C.2024' --境外
       END AS ITEM_NUM,
       SUM(C.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_DEPOSIT_S2601 C
       WHERE C.DATA_DATE = I_DATADATE
       GROUP BY C.ORG_NUM,
             CASE
               WHEN (C.REGION_CD LIKE '11%' AND C.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.C.2024'  --'%北京%'
               WHEN C.REGION_CD LIKE '12%' THEN 'S26_I_3_2.C.2024'  --'%天津%'
               WHEN C.REGION_CD LIKE '13%' THEN 'S26_I_3_3.C.2024'  --'%河北%'
               WHEN C.REGION_CD LIKE '14%' THEN 'S26_I_3_4.C.2024'  --'%山西%'
               WHEN C.REGION_CD LIKE '15%' THEN 'S26_I_3_5.C.2024'  --'%内蒙古
               WHEN C.REGION_CD LIKE '21%' THEN 'S26_I_3_6.C.2024'  --'%辽宁%'
               WHEN C.REGION_CD LIKE '22%' THEN 'S26_I_3_7.C.2024'  --'%吉林%'
               WHEN C.REGION_CD LIKE '23%' THEN 'S26_I_3_8.C.2024'  --'%黑龙江
               WHEN (C.REGION_CD LIKE '31%' OR C.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.C.2024'  --'%上海%'
               WHEN C.REGION_CD LIKE '32%' THEN 'S26_I_3_10.C.2024'  --'%江苏%'
               WHEN C.REGION_CD LIKE '33%' THEN 'S26_I_3_11.C.2024'  --'%浙江%'
               WHEN C.REGION_CD LIKE '34%' THEN 'S26_I_3_12.C.2024'  --'%安徽%'
               WHEN C.REGION_CD LIKE '35%' THEN 'S26_I_3_13.C.2024'  --'%福建%'
               WHEN C.REGION_CD LIKE '36%' THEN 'S26_I_3_14.C.2024'  --'%江西%'
               WHEN C.REGION_CD LIKE '37%' THEN 'S26_I_3_15.C.2024'  --'%山东%'
               WHEN C.REGION_CD LIKE '41%' THEN 'S26_I_3_16.C.2024'  --'%河南%'
               WHEN C.REGION_CD LIKE '42%' THEN 'S26_I_3_17.C.2024'  --'%湖北%'
               WHEN C.REGION_CD LIKE '43%' THEN 'S26_I_3_18.C.2024'  --'%湖南%'
               WHEN C.REGION_CD LIKE '44%' THEN 'S26_I_3_19.C.2024'  --'%广东%'
               WHEN C.REGION_CD LIKE '45%' THEN 'S26_I_3_20.C.2024'  --'%广西%'
               WHEN C.REGION_CD LIKE '46%' THEN 'S26_I_3_21.C.2024'  --'%海南%'
               WHEN C.REGION_CD LIKE '50%' THEN 'S26_I_3_22.C.2024'  --'%重庆%'
               WHEN C.REGION_CD LIKE '51%' THEN 'S26_I_3_23.C.2024'  --'%四川%'
               WHEN C.REGION_CD LIKE '52%' THEN 'S26_I_3_24.C.2024'  --'%贵州%'
               WHEN C.REGION_CD LIKE '53%' THEN 'S26_I_3_25.C.2024'  --'%云南%'
               WHEN C.REGION_CD LIKE '54%' THEN 'S26_I_3_26.C.2024'  --'%西藏%'
               WHEN C.REGION_CD LIKE '61%' THEN 'S26_I_3_27.C.2024'  --'%陕西%'
               WHEN C.REGION_CD LIKE '62%' THEN 'S26_I_3_28.C.2024'  --'%甘肃%'
               WHEN C.REGION_CD LIKE '63%' THEN 'S26_I_3_29.C.2024'  --'%青海%'
               WHEN C.REGION_CD LIKE '64%' THEN 'S26_I_3_30.C.2024'  --'%宁夏%'
               WHEN C.REGION_CD LIKE '65%' THEN 'S26_I_3_31.C.2024'  --'%新疆%'
               WHEN SUBSTR(C.REGION_CD,1,2) IN ('71','81','82') THEN 'S26_I_3_32.C.2024' --境外

           END
) q_0
INSERT INTO `S26_I_3_1.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_8.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_30.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_2.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_14.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_6.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_24.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_4.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_11.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_25.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_19.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_31.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_20.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_10.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_17.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_32.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_27.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_16.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_28.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_15.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_12.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_29.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_22.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_26.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_23.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_3.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_13.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_5.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_18.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_21.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_9.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_7.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 1: 共 18 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
           WHEN (A.REGION_CD_CUST LIKE '11%' AND A.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.B.2024'  --'%北京%'
           WHEN A.REGION_CD_CUST LIKE '12%' THEN 'S26_I_3_2.B.2024'  --'%天津%'
           WHEN A.REGION_CD_CUST LIKE '13%' THEN 'S26_I_3_3.B.2024'  --'%河北%'
           WHEN A.REGION_CD_CUST LIKE '14%' THEN 'S26_I_3_4.B.2024'  --'%山西%'
           WHEN A.REGION_CD_CUST LIKE '15%' THEN 'S26_I_3_5.B.2024'  --'%内蒙古
           WHEN A.REGION_CD_CUST LIKE '21%' THEN 'S26_I_3_6.B.2024'  --'%辽宁%'
           WHEN A.REGION_CD_CUST LIKE '22%' THEN 'S26_I_3_7.B.2024'  --'%吉林%'
           WHEN A.REGION_CD_CUST LIKE '23%' THEN 'S26_I_3_8.B.2024'  --'%黑龙江
           WHEN (A.REGION_CD_CUST LIKE '31%' OR A.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.B.2024'  --'%上海%'
           WHEN A.REGION_CD_CUST LIKE '32%' THEN 'S26_I_3_10.B.2024'  --'%江苏%'
           WHEN A.REGION_CD_CUST LIKE '33%' THEN 'S26_I_3_11.B.2024'  --'%浙江%'
           WHEN A.REGION_CD_CUST LIKE '34%' THEN 'S26_I_3_12.B.2024'  --'%安徽%'
           WHEN A.REGION_CD_CUST LIKE '35%' THEN 'S26_I_3_13.B.2024'  --'%福建%'
           WHEN A.REGION_CD_CUST LIKE '36%' THEN 'S26_I_3_14.B.2024'  --'%江西%'
           WHEN A.REGION_CD_CUST LIKE '37%' THEN 'S26_I_3_15.B.2024'  --'%山东%'
           WHEN A.REGION_CD_CUST LIKE '41%' THEN 'S26_I_3_16.B.2024'  --'%河南%'
           WHEN A.REGION_CD_CUST LIKE '42%' THEN 'S26_I_3_17.B.2024'  --'%湖北%'
           WHEN A.REGION_CD_CUST LIKE '43%' THEN 'S26_I_3_18.B.2024'  --'%湖南%'
           WHEN A.REGION_CD_CUST LIKE '44%' THEN 'S26_I_3_19.B.2024'  --'%广东%'
           WHEN A.REGION_CD_CUST LIKE '45%' THEN 'S26_I_3_20.B.2024'  --'%广西%'
           WHEN A.REGION_CD_CUST LIKE '46%' THEN 'S26_I_3_21.B.2024'  --'%海南%'
           WHEN A.REGION_CD_CUST LIKE '50%' THEN 'S26_I_3_22.B.2024'  --'%重庆%'
           WHEN A.REGION_CD_CUST LIKE '51%' THEN 'S26_I_3_23.B.2024'  --'%四川%'
           WHEN A.REGION_CD_CUST LIKE '52%' THEN 'S26_I_3_24.B.2024'  --'%贵州%'
           WHEN A.REGION_CD_CUST LIKE '53%' THEN 'S26_I_3_25.B.2024'  --'%云南%'
           WHEN A.REGION_CD_CUST LIKE '54%' THEN 'S26_I_3_26.B.2024'  --'%西藏%'
           WHEN A.REGION_CD_CUST LIKE '61%' THEN 'S26_I_3_27.B.2024'  --'%陕西%'
           WHEN A.REGION_CD_CUST LIKE '62%' THEN 'S26_I_3_28.B.2024'  --'%甘肃%'
           WHEN A.REGION_CD_CUST LIKE '63%' THEN 'S26_I_3_29.B.2024'  --'%青海%'
           WHEN A.REGION_CD_CUST LIKE '64%' THEN 'S26_I_3_30.B.2024'  --'%宁夏%'
           WHEN A.REGION_CD_CUST LIKE '65%' THEN 'S26_I_3_31.B.2024'  --'%新疆%'
           WHEN SUBSTR(A.REGION_CD_CUST,1,2) IN ('71','81','82') THEN 'S26_I_3_32.B.2024' --境外
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
         AND EXISTS (SELECT 1
                        FROM CBRC_TMP2_ACCT_LOAN_S2601 T
                       WHERE T.DATA_DATE = I_DATADATE
                         AND A.ACCT_NUM = T.ACCT_NUM)
       GROUP BY A.ORG_NUM,
             CASE
                 WHEN (A.REGION_CD_CUST LIKE '11%' AND A.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.B.2024'  --'%北京%'
                 WHEN A.REGION_CD_CUST LIKE '12%' THEN 'S26_I_3_2.B.2024'  --'%天津%'
                 WHEN A.REGION_CD_CUST LIKE '13%' THEN 'S26_I_3_3.B.2024'  --'%河北%'
                 WHEN A.REGION_CD_CUST LIKE '14%' THEN 'S26_I_3_4.B.2024'  --'%山西%'
                 WHEN A.REGION_CD_CUST LIKE '15%' THEN 'S26_I_3_5.B.2024'  --'%内蒙古
                 WHEN A.REGION_CD_CUST LIKE '21%' THEN 'S26_I_3_6.B.2024'  --'%辽宁%'
                 WHEN A.REGION_CD_CUST LIKE '22%' THEN 'S26_I_3_7.B.2024'  --'%吉林%'
                 WHEN A.REGION_CD_CUST LIKE '23%' THEN 'S26_I_3_8.B.2024'  --'%黑龙江
                 WHEN (A.REGION_CD_CUST LIKE '31%' OR A.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.B.2024'  --'%上海%'
                 WHEN A.REGION_CD_CUST LIKE '32%' THEN 'S26_I_3_10.B.2024'  --'%江苏%'
                 WHEN A.REGION_CD_CUST LIKE '33%' THEN 'S26_I_3_11.B.2024'  --'%浙江%'
                 WHEN A.REGION_CD_CUST LIKE '34%' THEN 'S26_I_3_12.B.2024'  --'%安徽%'
                 WHEN A.REGION_CD_CUST LIKE '35%' THEN 'S26_I_3_13.B.2024'  --'%福建%'
                 WHEN A.REGION_CD_CUST LIKE '36%' THEN 'S26_I_3_14.B.2024'  --'%江西%'
                 WHEN A.REGION_CD_CUST LIKE '37%' THEN 'S26_I_3_15.B.2024'  --'%山东%'
                 WHEN A.REGION_CD_CUST LIKE '41%' THEN 'S26_I_3_16.B.2024'  --'%河南%'
                 WHEN A.REGION_CD_CUST LIKE '42%' THEN 'S26_I_3_17.B.2024'  --'%湖北%'
                 WHEN A.REGION_CD_CUST LIKE '43%' THEN 'S26_I_3_18.B.2024'  --'%湖南%'
                 WHEN A.REGION_CD_CUST LIKE '44%' THEN 'S26_I_3_19.B.2024'  --'%广东%'
                 WHEN A.REGION_CD_CUST LIKE '45%' THEN 'S26_I_3_20.B.2024'  --'%广西%'
                 WHEN A.REGION_CD_CUST LIKE '46%' THEN 'S26_I_3_21.B.2024'  --'%海南%'
                 WHEN A.REGION_CD_CUST LIKE '50%' THEN 'S26_I_3_22.B.2024'  --'%重庆%'
                 WHEN A.REGION_CD_CUST LIKE '51%' THEN 'S26_I_3_23.B.2024'  --'%四川%'
                 WHEN A.REGION_CD_CUST LIKE '52%' THEN 'S26_I_3_24.B.2024'  --'%贵州%'
                 WHEN A.REGION_CD_CUST LIKE '53%' THEN 'S26_I_3_25.B.2024'  --'%云南%'
                 WHEN A.REGION_CD_CUST LIKE '54%' THEN 'S26_I_3_26.B.2024'  --'%西藏%'
                 WHEN A.REGION_CD_CUST LIKE '61%' THEN 'S26_I_3_27.B.2024'  --'%陕西%'
                 WHEN A.REGION_CD_CUST LIKE '62%' THEN 'S26_I_3_28.B.2024'  --'%甘肃%'
                 WHEN A.REGION_CD_CUST LIKE '63%' THEN 'S26_I_3_29.B.2024'  --'%青海%'
                 WHEN A.REGION_CD_CUST LIKE '64%' THEN 'S26_I_3_30.B.2024'  --'%宁夏%'
                 WHEN A.REGION_CD_CUST LIKE '65%' THEN 'S26_I_3_31.B.2024'  --'%新疆%'
                 WHEN SUBSTR(A.REGION_CD_CUST,1,2) IN ('71','81','82') THEN 'S26_I_3_32.B.2024' --境外
             END
) q_1
INSERT INTO `S26_I_3_5.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_23.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_3.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_25.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_19.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_8.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_11.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_15.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_29.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_10.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_21.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_16.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_17.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_4.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_9.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_22.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2.3.1.F.2024
INSERT INTO `S26_I_2.3.1.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_2.3.1.F.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
        AND A.TAG = 'SN'
      GROUP BY A.ORG_NUM;


-- ========== 逻辑组 3: 共 10 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.B.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.B.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.B.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.B.2024'
           END
         WHEN A.TAG1 = 'ZQ' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.C.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.C.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.C.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.C.2024'
           END
         WHEN A.TAG1 = 'FB' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.D.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.D.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.D.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.D.2024'
           END
         WHEN A.TAG1 = 'YC' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.G.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.G.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.G.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.G.2024'
           END
         WHEN A.TAG1 = 'CN' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.H.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.H.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.H.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.H.2024'
           END
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','ZQ','YC','CN','FB')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.B.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.B.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.B.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.B.2024'
                   END
                 WHEN A.TAG1 = 'ZQ' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.C.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.C.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.C.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.C.2024'
                   END
                 WHEN A.TAG1 = 'FB' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.D.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.D.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.D.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.D.2024'
                   END
                 WHEN A.TAG1 = 'YC' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.G.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.G.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.G.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.G.2024'
                   END
                 WHEN A.TAG1 = 'CN' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.H.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.H.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.H.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.H.2024'
                   END
               END
) q_3
INSERT INTO `S26_I_1.1.2.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.2.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.1.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.1.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.3.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.4.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.3.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.1.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 4: 共 3 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_2.3.1.B.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_2.3.1.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_2.3.1.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_2.3.1.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','YC','CN','FB')
        AND A.TAG = 'SN'
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_2.3.1.B.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_2.3.1.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_2.3.1.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_2.3.1.H.2024'
               END
) q_4
INSERT INTO `S26_I_2.3.1.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.3.1.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.3.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 5: 共 30 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
           WHEN (A.REGION_CD_CUST LIKE '11%' AND A.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.A.2024'  --'%北京%'
           WHEN A.REGION_CD_CUST LIKE '12%' THEN 'S26_I_3_2.A.2024'  --'%天津%'
           WHEN A.REGION_CD_CUST LIKE '13%' THEN 'S26_I_3_3.A.2024'  --'%河北%'
           WHEN A.REGION_CD_CUST LIKE '14%' THEN 'S26_I_3_4.A.2024'  --'%山西%'
           WHEN A.REGION_CD_CUST LIKE '15%' THEN 'S26_I_3_5.A.2024'  --'%内蒙古
           WHEN A.REGION_CD_CUST LIKE '21%' THEN 'S26_I_3_6.A.2024'  --'%辽宁%'
           WHEN A.REGION_CD_CUST LIKE '22%' THEN 'S26_I_3_7.A.2024'  --'%吉林%'
           WHEN A.REGION_CD_CUST LIKE '23%' THEN 'S26_I_3_8.A.2024'  --'%黑龙江
           WHEN (A.REGION_CD_CUST LIKE '31%' OR A.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.A.2024'  --'%上海%'
           WHEN A.REGION_CD_CUST LIKE '32%' THEN 'S26_I_3_10.A.2024'  --'%江苏%'
           WHEN A.REGION_CD_CUST LIKE '33%' THEN 'S26_I_3_11.A.2024'  --'%浙江%'
           WHEN A.REGION_CD_CUST LIKE '34%' THEN 'S26_I_3_12.A.2024'  --'%安徽%'
           WHEN A.REGION_CD_CUST LIKE '35%' THEN 'S26_I_3_13.A.2024'  --'%福建%'
           WHEN A.REGION_CD_CUST LIKE '36%' THEN 'S26_I_3_14.A.2024'  --'%江西%'
           WHEN A.REGION_CD_CUST LIKE '37%' THEN 'S26_I_3_15.A.2024'  --'%山东%'
           WHEN A.REGION_CD_CUST LIKE '41%' THEN 'S26_I_3_16.A.2024'  --'%河南%'
           WHEN A.REGION_CD_CUST LIKE '42%' THEN 'S26_I_3_17.A.2024'  --'%湖北%'
           WHEN A.REGION_CD_CUST LIKE '43%' THEN 'S26_I_3_18.A.2024'  --'%湖南%'
           WHEN A.REGION_CD_CUST LIKE '44%' THEN 'S26_I_3_19.A.2024'  --'%广东%'
           WHEN A.REGION_CD_CUST LIKE '45%' THEN 'S26_I_3_20.A.2024'  --'%广西%'
           WHEN A.REGION_CD_CUST LIKE '46%' THEN 'S26_I_3_21.A.2024'  --'%海南%'
           WHEN A.REGION_CD_CUST LIKE '50%' THEN 'S26_I_3_22.A.2024'  --'%重庆%'
           WHEN A.REGION_CD_CUST LIKE '51%' THEN 'S26_I_3_23.A.2024'  --'%四川%'
           WHEN A.REGION_CD_CUST LIKE '52%' THEN 'S26_I_3_24.A.2024'  --'%贵州%'
           WHEN A.REGION_CD_CUST LIKE '53%' THEN 'S26_I_3_25.A.2024'  --'%云南%'
           WHEN A.REGION_CD_CUST LIKE '54%' THEN 'S26_I_3_26.A.2024'  --'%西藏%'
           WHEN A.REGION_CD_CUST LIKE '61%' THEN 'S26_I_3_27.A.2024'  --'%陕西%'
           WHEN A.REGION_CD_CUST LIKE '62%' THEN 'S26_I_3_28.A.2024'  --'%甘肃%'
           WHEN A.REGION_CD_CUST LIKE '63%' THEN 'S26_I_3_29.A.2024'  --'%青海%'
           WHEN A.REGION_CD_CUST LIKE '64%' THEN 'S26_I_3_30.A.2024'  --'%宁夏%'
           WHEN A.REGION_CD_CUST LIKE '65%' THEN 'S26_I_3_31.A.2024'  --'%新疆%'
           WHEN SUBSTR(A.REGION_CD_CUST,1,2) IN ('71','81','82') THEN 'S26_I_3_32.A.2024' --境外
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
       GROUP BY A.ORG_NUM,
             CASE
                 WHEN (A.REGION_CD_CUST LIKE '11%' AND A.ACCT_NUM <> 'N000310000024539') THEN 'S26_I_3_1.A.2024'  --'%北京%'
                 WHEN A.REGION_CD_CUST LIKE '12%' THEN 'S26_I_3_2.A.2024'  --'%天津%'
                 WHEN A.REGION_CD_CUST LIKE '13%' THEN 'S26_I_3_3.A.2024'  --'%河北%'
                 WHEN A.REGION_CD_CUST LIKE '14%' THEN 'S26_I_3_4.A.2024'  --'%山西%'
                 WHEN A.REGION_CD_CUST LIKE '15%' THEN 'S26_I_3_5.A.2024'  --'%内蒙古
                 WHEN A.REGION_CD_CUST LIKE '21%' THEN 'S26_I_3_6.A.2024'  --'%辽宁%'
                 WHEN A.REGION_CD_CUST LIKE '22%' THEN 'S26_I_3_7.A.2024'  --'%吉林%'
                 WHEN A.REGION_CD_CUST LIKE '23%' THEN 'S26_I_3_8.A.2024'  --'%黑龙江
                 WHEN (A.REGION_CD_CUST LIKE '31%' OR A.ACCT_NUM = 'N000310000024539') THEN 'S26_I_3_9.A.2024'  --'%上海%'
                 WHEN A.REGION_CD_CUST LIKE '32%' THEN 'S26_I_3_10.A.2024'  --'%江苏%'
                 WHEN A.REGION_CD_CUST LIKE '33%' THEN 'S26_I_3_11.A.2024'  --'%浙江%'
                 WHEN A.REGION_CD_CUST LIKE '34%' THEN 'S26_I_3_12.A.2024'  --'%安徽%'
                 WHEN A.REGION_CD_CUST LIKE '35%' THEN 'S26_I_3_13.A.2024'  --'%福建%'
                 WHEN A.REGION_CD_CUST LIKE '36%' THEN 'S26_I_3_14.A.2024'  --'%江西%'
                 WHEN A.REGION_CD_CUST LIKE '37%' THEN 'S26_I_3_15.A.2024'  --'%山东%'
                 WHEN A.REGION_CD_CUST LIKE '41%' THEN 'S26_I_3_16.A.2024'  --'%河南%'
                 WHEN A.REGION_CD_CUST LIKE '42%' THEN 'S26_I_3_17.A.2024'  --'%湖北%'
                 WHEN A.REGION_CD_CUST LIKE '43%' THEN 'S26_I_3_18.A.2024'  --'%湖南%'
                 WHEN A.REGION_CD_CUST LIKE '44%' THEN 'S26_I_3_19.A.2024'  --'%广东%'
                 WHEN A.REGION_CD_CUST LIKE '45%' THEN 'S26_I_3_20.A.2024'  --'%广西%'
                 WHEN A.REGION_CD_CUST LIKE '46%' THEN 'S26_I_3_21.A.2024'  --'%海南%'
                 WHEN A.REGION_CD_CUST LIKE '50%' THEN 'S26_I_3_22.A.2024'  --'%重庆%'
                 WHEN A.REGION_CD_CUST LIKE '51%' THEN 'S26_I_3_23.A.2024'  --'%四川%'
                 WHEN A.REGION_CD_CUST LIKE '52%' THEN 'S26_I_3_24.A.2024'  --'%贵州%'
                 WHEN A.REGION_CD_CUST LIKE '53%' THEN 'S26_I_3_25.A.2024'  --'%云南%'
                 WHEN A.REGION_CD_CUST LIKE '54%' THEN 'S26_I_3_26.A.2024'  --'%西藏%'
                 WHEN A.REGION_CD_CUST LIKE '61%' THEN 'S26_I_3_27.A.2024'  --'%陕西%'
                 WHEN A.REGION_CD_CUST LIKE '62%' THEN 'S26_I_3_28.A.2024'  --'%甘肃%'
                 WHEN A.REGION_CD_CUST LIKE '63%' THEN 'S26_I_3_29.A.2024'  --'%青海%'
                 WHEN A.REGION_CD_CUST LIKE '64%' THEN 'S26_I_3_30.A.2024'  --'%宁夏%'
                 WHEN A.REGION_CD_CUST LIKE '65%' THEN 'S26_I_3_31.A.2024'  --'%新疆%'
                 WHEN SUBSTR(A.REGION_CD_CUST,1,2) IN ('71','81','82') THEN 'S26_I_3_32.A.2024' --境外
             END
) q_5
INSERT INTO `S26_I_3_15.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_10.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_1.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_21.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_18.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_3.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_12.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_25.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_26.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_4.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_5.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_6.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_22.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_28.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_17.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_31.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_16.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_29.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_24.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_8.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_2.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_11.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_30.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_27.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_19.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_20.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_13.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_9.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_14.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_3_23.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.1.1.A.2024
INSERT INTO `S26_I_2_3.1.1.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_2_3.1.1.A.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
         AND A.TAG1 = 'Y' --设有分支机构
       GROUP BY A.ORG_NUM;


-- ========== 逻辑组 7: 共 4 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_1.3.1.B.2024'
         WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.3.1.C.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_1.3.1.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_1.3.1.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_1.3.1.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','ZQ','YC','CN','FB')
        AND A.TAG = 'SN' --省内业务
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_1.3.1.B.2024'
                 WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.3.1.C.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_1.3.1.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_1.3.1.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_1.3.1.H.2024'
               END
) q_7
INSERT INTO `S26_I_1.3.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.3.1.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.3.1.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.3.1.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 8: 共 4 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_1.2.2.B.2024'
         WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.2.2.C.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_1.2.2.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_1.2.2.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_1.2.2.H.2024'
       END AS ITEM_NUM,
       --SUM(DECODE(A.TAG1,'DK',NVL(A.PRIN_FINAL_RESLT,0),'ZQ',NVL(A.PRIN_FINAL_RESLT,0),NVL(A.OFBS_FINAL_RESLT,0))) AS ITEM_VAL,
       SUM(NVL(A.PRIN_FINAL_RESLT,0)+NVL(A.OFBS_FINAL_RESLT,0)) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','ZQ','YC','CN','FB')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_1.2.2.B.2024'
                 WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.2.2.C.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_1.2.2.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_1.2.2.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_1.2.2.H.2024'
               END
) q_8
INSERT INTO `S26_I_1.2.2.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.2.2.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.2.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.2.2.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 9: 共 4 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN (A.MATUR_DATE IS NULL OR MONTHS_BETWEEN(A.MATUR_DATE, A.ST_INT_DT) <= 6) THEN
          'S26_I_2_4.1.A.2024' -- 活期和六个月以内（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 6 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 12 THEN
          'S26_I_2_4.2.A.2024' -- 六个月至一年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 12 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 36 THEN
          'S26_I_2_4.3.A.2024' -- 一年至三年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 36 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 60 THEN
          'S26_I_2_4.4.A.2024' -- 三年至五年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 60 THEN
          'S26_I_2_4.5.A.2024' -- 五年以上
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
       GROUP BY A.ORG_NUM,
                 CASE
         WHEN (A.MATUR_DATE IS NULL OR MONTHS_BETWEEN(A.MATUR_DATE, A.ST_INT_DT) <= 6) THEN
          'S26_I_2_4.1.A.2024' -- 活期和六个月以内（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 6 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 12 THEN
          'S26_I_2_4.2.A.2024' -- 六个月至一年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 12 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 36 THEN
          'S26_I_2_4.3.A.2024' -- 一年至三年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 36 AND MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) <= 60 THEN
          'S26_I_2_4.4.A.2024' -- 三年至五年（含）
         WHEN MONTHS_BETWEEN(DATE(A.MATUR_DATE), DATE(A.ST_INT_DT)) > 60 THEN
          'S26_I_2_4.5.A.2024' -- 五年以上
       END
) q_9
INSERT INTO `S26_I_2_4.2.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_4.4.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_4.1.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_4.3.A.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.1.2.A.2024
INSERT INTO `S26_I_2_3.1.2.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_2_3.1.2.A.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
         AND A.TAG1 = 'N' --未设分支机构
       GROUP BY A.ORG_NUM;


-- 指标: S26_I_2_3.1.2.B.2024
INSERT INTO `S26_I_2_3.1.2.B.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT 
      I_DATADATE AS DATA_DATE,
      A.ORG_NUM AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_I' AS REP_NUM,
      'S26_I_2_3.1.2.B.2024' AS ITEM_NUM,
      SUM(A.BALANCE) AS ITEM_VAL,
      '2' AS FLAG
       FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       LEFT JOIN SMTMODS_L_CUST_C C
         ON A.CUST_ID = C.CUST_ID
        AND A.DATA_DATE = C.DATA_DATE
      WHERE A.DATA_DATE = I_DATADATE
        AND C.DEPOSIT_CUSTTYPE NOT IN ('13', '14') --排除个体工商户
        AND (SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201102'
           or  A.GL_ITEM_CODE IN ('22410101','20110301','20110302','20110303','20080101','20090101'))--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
          
        AND A.TAG1 = 'N' --未设分支机构
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_1.7.4.A.2024
INSERT INTO `S26_I_1.7.4.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT I_DATADATE AS DATA_DATE,
             '009816' AS ORG_NUM,
             'CBRC' AS SYS_NAM,
             'S26_I' AS REP_NUM,
             'S26_I_1.7.4.A.2024' AS ITEM_NUM,
             BALANCE AS ITEM_VAL,
             '2' AS FLAG
     FROM CBRC_FAMS_S26_REPORT T
     WHERE T.DATA_DATE = I_DATADATE;


-- ========== 逻辑组 13: 共 2 个指标 ==========
FROM (
SELECT 
     I_DATADATE AS DATA_DATE,
     ORG_NUM AS ORG_NUM,
     'CBRC' AS SYS_NAM,
     'S26_I' AS REP_NUM,
     ITEM_NUM AS ITEM_NUM,
     SUM(ITEM_VAL) AS ITEM_VAL,
     '2' AS FLAG
      FROM (SELECT 
             A.ORG_NUM AS ORG_NUM,
             A.CUST_ID AS CUST_ID,
             CASE
               WHEN SUM(A.BALANCE) <= 50000000 THEN
                'S26_I_2_3.2.3.B.2024'
               WHEN SUM(A.BALANCE) > 50000000 THEN
                'S26_I_2_3.2.4.B.2024'
             END AS ITEM_NUM,
             SUM(A.BALANCE) AS ITEM_VAL
              FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
              LEFT JOIN SMTMODS_L_CUST_C C
                ON A.CUST_ID = C.CUST_ID
               AND A.DATA_DATE = C.DATA_DATE
             WHERE A.DATA_DATE = I_DATADATE
               AND C.DEPOSIT_CUSTTYPE NOT IN ('13', '14') --排除个体工商户
               AND (SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201102'
               OR A.GL_ITEM_CODE    IN ('22410101','20110301','20110302','20110303','20080101','20090101')--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
                   )
             GROUP BY A.ORG_NUM, A.CUST_ID)
     GROUP BY ORG_NUM, ITEM_NUM
) q_13
INSERT INTO `S26_I_2_3.2.3.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_3.2.4.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_1.5.A.2024
--关联企业 依赖G15
    INSERT INTO `S26_I_1.5.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
        SELECT
         I_DATADATE AS DATA_DATE,
         B.ORG_CODE AS ORG_NUM,
         'CBRC' AS SYS_NAM,
         'S26_I' AS REP_NUM,
         'S26_I_1.5.A.2024' AS ITEM_NUM,
         SUM(T.BALANCE) AS ITEM_VAL,
         '2' AS FLAG
        FROM (SELECT 
                L.ORG_NUM, SUM(L.LOAN_ACCT_BAL) BALANCE --贷款余额
                FROM CBRC_TM_CBRC_G15_TEMP1 G
               INNER JOIN SMTMODS_L_CUST_C A
                  ON G.ID_NO = A.ID_NO
                 AND A.DATA_DATE = G.DDATE
               INNER JOIN SMTMODS_L_ACCT_LOAN L
                  ON A.CUST_ID = L.CUST_ID
                 AND L.DATA_DATE = A.DATA_DATE
                 AND L.LOAN_ACCT_BAL <> 0
                 AND L.ACCT_TYP NOT LIKE '90%'
               WHERE A.DATA_DATE = I_DATADATE
                 AND L.CANCEL_FLG = 'N'
          AND L.LOAN_STOCKEN_DATE IS NULL    --add by haorui 20250311 JLBA202408200012 资产未转让
                 AND LENGTHB(L.ACCT_NUM) < 36
                 AND SUBSTR(A.CUST_TYP, 1, 1) IN ('0', '1') --企业
                 AND A.CORP_BUSINSESS_TYPE NOT LIKE 'J%' --非金融企业
                 AND SUBSTR(NVL(A.REGION_CD, A.ORG_AREA), 1, 2) <> '22' --去吉林  空值暂时不取
               GROUP BY L.ORG_NUM) T
       INNER JOIN cbrc_TM_L_ORG_FLAT B
          ON T.ORG_NUM = B.SUB_ORG_CODE
       GROUP BY B.ORG_CODE;

UPDATE CBRC_A_REPT_ITEM_VAL
        SET IS_TOTAL = 'N'
      WHERE DATA_DATE = I_DATADATE
        AND REP_NUM = 'S26_I'
        AND ITEM_NUM IN (--集团相关不需要汇总。已在逻辑中处理
                         'S26_I_1.6.A.2024',
                         'S26_I_1.5.A.2024',
                         --存款前十大不需要汇总。已在逻辑中处理
                         'S26_I_2.5.A.2024',
                         'S26_I_2.5.B.2024',
                         'S26_I_2.5.C.2024',
                         'S26_I_2.5.D.2024',
                         'S26_I_2.5.E.2024',
                         'S26_I_2.5.F.2024'
                         );


-- 指标: S26_I_2.3.2.B.2024
INSERT INTO `S26_I_2.3.2.B.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_2.3.2.B.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_2.3.2.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_2.3.2.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_2.3.2.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','YC','CN','FB')
        AND A.TAG = 'SY'
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_2.3.2.B.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_2.3.2.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_2.3.2.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_2.3.2.H.2024'
               END;


-- ========== 逻辑组 16: 共 3 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_1.2.1.B.2024'
         WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.2.1.C.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_1.2.1.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_1.2.1.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_1.2.1.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','ZQ','YC','CN','FB')
        AND A.LOAN_GRADE_CD IN ('3','4','5') --五级分类：次级 可疑 损失
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_1.2.1.B.2024'
                 WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.2.1.C.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_1.2.1.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_1.2.1.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_1.2.1.H.2024'
               END
) q_16
INSERT INTO `S26_I_1.2.1.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.2.1.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.2.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.3.1.C.2024
INSERT INTO `S26_I_2_3.3.1.C.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT I_DATADATE AS DATA_DATE,
            ORG_NUM AS ORG_NUM,
            'CBRC' AS SYS_NAM,
            'S26_I' AS REP_NUM,
            'S26_I_2_3.3.1.C.2024' AS ITEM_NUM,
            SUM(ACCT_BALANCE) AS ITEM_VAL,
            '2' AS FLAG
       FROM (
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
           WHERE A.DATA_DATE = I_DATADATE
             AND (SUBSTR(A.GL_ITEM_CODE,1,6) = '201101'
               OR A.GL_ITEM_CODE ='22410102' )--[JLBA202507210012][石雨][修改内容：22410102个人久悬未取款]
          UNION ALL
          --省外单位个体工商户存款
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
            LEFT JOIN SMTMODS_L_CUST_C C
              ON A.CUST_ID = C.CUST_ID
             AND A.DATA_DATE = C.DATA_DATE
           WHERE A.DATA_DATE = I_DATADATE
             AND C.DEPOSIT_CUSTTYPE IN ('13','14') --个体工商户
             AND (SUBSTR(A.GL_ITEM_CODE,1,6) = '201102'
               OR A.GL_ITEM_CODE    IN ('22410101','20110301','20110302','20110303')--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
                   )
             
             )
      GROUP BY ORG_NUM;


-- ========== 逻辑组 18: 共 2 个指标 ==========
FROM (
SELECT 
     I_DATADATE AS DATA_DATE,
     ORG_NUM AS ORG_NUM,
     'CBRC' AS SYS_NAM,
     'S26_I' AS REP_NUM,
     ITEM_NUM AS ITEM_NUM,
     SUM(ITEM_VAL) AS ITEM_VAL,
     '2' AS FLAG
      FROM (SELECT 
             A.ORG_NUM AS ORG_NUM,
             A.CUST_ID AS CUST_ID,
             CASE
               WHEN SUM(A.BALANCE) <= 500000 THEN
                'S26_I_2_3.2.1.B.2024'
               WHEN SUM(A.BALANCE) > 500000 THEN
                'S26_I_2_3.2.2.B.2024'
             END AS ITEM_NUM,
             SUM(A.BALANCE) AS ITEM_VAL
              FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
              LEFT JOIN SMTMODS_L_CUST_C C
                ON A.CUST_ID = C.CUST_ID
               AND A.DATA_DATE = C.DATA_DATE
             WHERE A.DATA_DATE = I_DATADATE
               AND C.DEPOSIT_CUSTTYPE NOT IN ('13', '14') --排除个体工商户
               AND (SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201102'
                   OR A.GL_ITEM_CODE    IN ('22410101','20110301','20110302','20110303','20080101','20090101')--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
                   )
             GROUP BY A.ORG_NUM, A.CUST_ID)
     GROUP BY ORG_NUM, ITEM_NUM
) q_18
INSERT INTO `S26_I_2_3.2.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_3.2.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 19: 共 3 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_2.2.2.B.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_2.2.2.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_2.2.2.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_2.2.2.H.2024'
       END AS ITEM_NUM,
       SUM(NVL(A.PRIN_FINAL_RESLT,0)+NVL(A.OFBS_FINAL_RESLT,0)) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','YC','CN','FB')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_2.2.2.B.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_2.2.2.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_2.2.2.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_2.2.2.H.2024'
               END
) q_19
INSERT INTO `S26_I_2.2.2.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.2.2.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.2.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.1.1.B.2024
INSERT INTO `S26_I_2_3.1.1.B.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT 
      I_DATADATE AS DATA_DATE,
      A.ORG_NUM AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_I' AS REP_NUM,
      'S26_I_2_3.1.1.B.2024' AS ITEM_NUM,
      SUM(A.BALANCE) AS ITEM_VAL,
      '2' AS FLAG
       FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       LEFT JOIN SMTMODS_L_CUST_C C
         ON A.CUST_ID = C.CUST_ID
        AND A.DATA_DATE = C.DATA_DATE
      WHERE A.DATA_DATE = I_DATADATE
        AND C.DEPOSIT_CUSTTYPE NOT IN ('13', '14') --排除个体工商户
        AND SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201102'
        AND A.TAG1 = 'Y' --设有分支机构
      GROUP BY A.ORG_NUM;


-- ========== 逻辑组 21: 共 6 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.B.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.B.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.B.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.B.2024'
           END
         WHEN A.TAG1 = 'FB' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.D.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.D.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.D.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.D.2024'
           END
         WHEN A.TAG1 = 'YC' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.G.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.G.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.G.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.G.2024'
           END
         WHEN A.TAG1 = 'CN' THEN
           CASE
             WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.H.2024'
             WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.H.2024'
             WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.H.2024'
             WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.H.2024'
           END
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','YC','CN','FB')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.B.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.B.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.B.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.B.2024'
                   END
                 WHEN A.TAG1 = 'FB' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.D.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.D.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.D.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.D.2024'
                   END
                 WHEN A.TAG1 = 'YC' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.G.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.G.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.G.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.G.2024'
                   END
                 WHEN A.TAG1 = 'CN' THEN
                   CASE
                     WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.H.2024'
                     WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.H.2024'
                     WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.H.2024'
                     WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.H.2024'
                   END
               END
) q_21
INSERT INTO `S26_I_2.1.4.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.1.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.1.3.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.1.1.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.1.2.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2.1.1.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- ========== 逻辑组 22: 共 2 个指标 ==========
FROM (
SELECT 
             I_DATADATE AS DATA_DATE,
             ORG_NUM AS ORG_NUM,
             'CBRC' AS SYS_NAM,
             'S26_I' AS REP_NUM,
             ITEM_NUM AS ITEM_NUM,
             SUM(ITEM_VAL) AS ITEM_VAL,
             '2' AS FLAG
        FROM (SELECT 
               A.ORG_NUM,
               A.CUST_ID,
               CASE
                 WHEN SUM(A.BALANCE) <= 500000 THEN
                  'S26_I_2_3.2.1.C.2024'
                 WHEN SUM(A.BALANCE) > 500000 THEN
                  'S26_I_2_3.2.2.C.2024'
               END ITEM_NUM,
               SUM(A.BALANCE) ITEM_VAL
                FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
               WHERE A.DATA_DATE = I_DATADATE
                 AND ( SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201101'
                   OR A.GL_ITEM_CODE ='22410102' )--[JLBA202507210012][石雨][修改内容：22410102个人久悬未取款]
               GROUP BY A.ORG_NUM, A.CUST_ID
              UNION ALL
              SELECT 
               A.ORG_NUM,
               A.CUST_ID,
               CASE
                 WHEN SUM(A.BALANCE) <= 500000 THEN
                  'S26_I_2_3.2.1.C.2024'
                 WHEN SUM(A.BALANCE) > 500000 THEN
                  'S26_I_2_3.2.2.C.2024'
               END ITEM_NUM,
               SUM(A.BALANCE) ITEM_VAL
                FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
                LEFT JOIN SMTMODS_L_CUST_C C
                  ON A.CUST_ID = C.CUST_ID
                 AND A.DATA_DATE = C.DATA_DATE
               WHERE A.DATA_DATE = I_DATADATE
                 AND C.DEPOSIT_CUSTTYPE IN ('13', '14') --个体工商户
                 AND (SUBSTR(A.GL_ITEM_CODE, 1, 6) = '201102'
                      OR A.GL_ITEM_CODE    IN ('22410101','20110301','20110302','20110303')--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
                   )
               GROUP BY A.ORG_NUM, A.CUST_ID)
       GROUP BY ORG_NUM, ITEM_NUM
) q_22
INSERT INTO `S26_I_2_3.2.1.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_2_3.2.2.C.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.1.1.D.2024
INSERT INTO `S26_I_2_3.1.1.D.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT 
      I_DATADATE AS DATA_DATE,
      A.ORG_NUM AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_I' AS REP_NUM,
      'S26_I_2_3.1.1.D.2024' AS ITEM_NUM,
      SUM(A.BALANCE) AS ITEM_VAL,
      '2' AS FLAG
       FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
      WHERE A.DATA_DATE = I_DATADATE
        AND A.GL_ITEM_CODE IN ('20120106', '20120204')
        AND A.TAG1 = 'Y' --设有分支机构
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_2.2.2.F.2024
INSERT INTO `S26_I_2.2.2.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_2.2.2.F.2024' AS ITEM_NUM,
       SUM(NVL(A.PRIN_FINAL_RESLT,0)+NVL(A.OFBS_FINAL_RESLT,0)) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
      GROUP BY A.ORG_NUM;


-- ========== 逻辑组 25: 共 2 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.F.2024'
         WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.F.2024'
         WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.F.2024'
         WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.F.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.MATUR_DATE = '1' THEN 'S26_I_1.1.1.F.2024'
                 WHEN A.MATUR_DATE = '2' THEN 'S26_I_1.1.2.F.2024'
                 WHEN A.MATUR_DATE = '3' THEN 'S26_I_1.1.3.F.2024'
                 WHEN A.MATUR_DATE = '4' THEN 'S26_I_1.1.4.F.2024'
               END
) q_25
INSERT INTO `S26_I_1.1.1.F.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.1.2.F.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_2_3.1.1.C.2024
INSERT INTO `S26_I_2_3.1.1.C.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT I_DATADATE AS DATA_DATE,
            ORG_NUM AS ORG_NUM,
            'CBRC' AS SYS_NAM,
            'S26_I' AS REP_NUM,
            'S26_I_2_3.1.1.C.2024' AS ITEM_NUM,
            SUM(ACCT_BALANCE) AS ITEM_VAL,
            '2' AS FLAG
       FROM (
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
           WHERE A.DATA_DATE = I_DATADATE
             AND SUBSTR(A.GL_ITEM_CODE,1,6) = '201101'
             AND A.TAG1 = 'Y' --设有分支机构
          UNION ALL
          --省外单位个体工商户存款
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
            LEFT JOIN SMTMODS_L_CUST_C C
              ON A.CUST_ID = C.CUST_ID
             AND A.DATA_DATE = C.DATA_DATE
           WHERE A.DATA_DATE = I_DATADATE
             AND C.DEPOSIT_CUSTTYPE IN ('13','14') --个体工商户
             AND SUBSTR(A.GL_ITEM_CODE,1,6) = '201102'
             AND A.TAG1 = 'Y' --设有分支机构
             )
      GROUP BY ORG_NUM;


-- 指标: S26_I_2.2.1.D.2024
INSERT INTO `S26_I_2.2.1.D.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_2.2.1.B.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_2.2.1.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_2.2.1.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_2.2.1.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','YC','CN','FB')
        AND A.LOAN_GRADE_CD IN ('3','4','5')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_2.2.1.B.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_2.2.1.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_2.2.1.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_2.2.1.H.2024'
               END;


-- 指标: S26_I_1.3.1.F.2024
INSERT INTO `S26_I_1.3.1.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.3.1.F.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
        AND A.TAG = 'SN' --省内业务
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_1.3.2.F.2024
INSERT INTO `S26_I_1.3.2.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.3.2.F.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
        AND A.TAG = 'SY' --省外业务
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_1.6.A.2024
INSERT INTO `S26_I_1.6.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
    SELECT 
     I_DATADATE AS DATA_DATE,
     ORG_NUM AS ORG_NUM,
     'CBRC' AS SYS_NAM,
     'S26_I' AS REP_NUM,
     'S26_I_1.6.A.2024' AS ITEM_NUM,
     SUM(LOAN_ACCT_BAL) AS ITEM_VAL,
     '2' AS FLAG
      FROM (SELECT T2.ORG_NUM, T2.CUST_GROUP_NO, T2.LOAN_ACCT_BAL, SEQ_NO
              FROM (SELECT T1.*,
                           ROW_NUMBER() OVER(PARTITION BY T1.ORG_NUM ORDER BY T1.LOAN_ACCT_BAL DESC, T1.ORG_NUM, T1.CUST_GROUP_NO) AS SEQ_NO
                      FROM (SELECT B.ORG_CODE AS ORG_NUM,
                                   T.CUST_GROUP_NO,
                                   SUM(LOAN_ACCT_BAL) LOAN_ACCT_BAL
                              FROM (SELECT 
                                     A.ORG_NUM AS ORG_NUM,
                                     D.CUST_GROUP_NO AS CUST_GROUP_NO,
                                     SUM(A.BALANCE) AS LOAN_ACCT_BAL
                                      FROM CBRC_TMP_ACCT_LOAN_S2601 A
                                     INNER JOIN SMTMODS_L_CUST_C_GROUP_MEM B --集团成员信息
                                        ON A.CUST_ID = B.GROUP_MEM_NO --成员代码
                                       AND B.DATA_DATE = I_DATADATE
                                     INNER JOIN SMTMODS_L_CUST_C C
                                        ON A.CUST_ID = C.CUST_ID
                                       AND C.DATA_DATE = I_DATADATE
                                     INNER JOIN SMTMODS_L_CUST_C_GROUP_INFO D
                                        ON B.CUST_GROUP_NO = D.CUST_GROUP_NO
                                       AND D.DATA_DATE = I_DATADATE
                                     WHERE A.DATA_DATE = I_DATADATE
                                     GROUP BY A.ORG_NUM, D.CUST_GROUP_NO) T
                             INNER JOIN CBRC_TM_L_ORG_FLAT B
                                ON T.ORG_NUM = B.SUB_ORG_CODE
                             GROUP BY B.ORG_CODE, T.CUST_GROUP_NO) T1) T2
             WHERE SEQ_NO <= 10)
     GROUP BY ORG_NUM;

UPDATE CBRC_A_REPT_ITEM_VAL
        SET IS_TOTAL = 'N'
      WHERE DATA_DATE = I_DATADATE
        AND REP_NUM = 'S26_I'
        AND ITEM_NUM IN (--集团相关不需要汇总。已在逻辑中处理
                         'S26_I_1.6.A.2024',
                         'S26_I_1.5.A.2024',
                         --存款前十大不需要汇总。已在逻辑中处理
                         'S26_I_2.5.A.2024',
                         'S26_I_2.5.B.2024',
                         'S26_I_2.5.C.2024',
                         'S26_I_2.5.D.2024',
                         'S26_I_2.5.E.2024',
                         'S26_I_2.5.F.2024'
                         );


-- 指标: S26_I_2_3.1.2.C.2024
INSERT INTO `S26_I_2_3.1.2.C.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT I_DATADATE AS DATA_DATE,
            ORG_NUM AS ORG_NUM,
            'CBRC' AS SYS_NAM,
            'S26_I' AS REP_NUM,
            'S26_I_2_3.1.2.C.2024' AS ITEM_NUM,
            SUM(ACCT_BALANCE) AS ITEM_VAL,
            '2' AS FLAG
       FROM (
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
           WHERE A.DATA_DATE = I_DATADATE
             AND (SUBSTR(A.GL_ITEM_CODE,1,6) = '201101' OR A.GL_ITEM_CODE ='22410102') --[JLBA202507210012][石雨][修改内容：22410102个人久悬未取款]
             AND A.TAG1 = 'N' --未设分支机构
          UNION ALL
          --省外单位个体工商户存款
          SELECT A.ORG_NUM,A.BALANCE ACCT_BALANCE
            FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
            LEFT JOIN SMTMODS_L_CUST_C C
              ON A.CUST_ID = C.CUST_ID
             AND A.DATA_DATE = C.DATA_DATE
           WHERE A.DATA_DATE = I_DATADATE
             AND C.DEPOSIT_CUSTTYPE IN ('13','14') --个体工商户
             AND (SUBSTR(A.GL_ITEM_CODE,1,6) = '201102'
                OR A.GL_ITEM_CODE IN ('22410101','20110301','20110302','20110303') )--[JLBA202507210012][石雨][修改内容：22410101单位久悬未取款、201103（财政性存款）调整为 一般单位活期存款]
             AND A.TAG1 = 'N' --未设分支机构
             )
      GROUP BY ORG_NUM;


-- 指标: S26_I_1.2.2.F.2024
INSERT INTO `S26_I_1.2.2.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.2.2.F.2024' AS ITEM_NUM,
       SUM(NVL(A.PRIN_FINAL_RESLT,0)+NVL(A.OFBS_FINAL_RESLT,0)) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
      GROUP BY A.ORG_NUM;


-- ========== 逻辑组 33: 共 3 个指标 ==========
FROM (
SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.TAG1 = 'DK' THEN 'S26_I_1.3.2.B.2024'
         WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.3.2.C.2024'
         WHEN A.TAG1 = 'FB' THEN 'S26_I_1.3.2.D.2024'
         WHEN A.TAG1 = 'YC' THEN 'S26_I_1.3.2.G.2024'
         WHEN A.TAG1 = 'CN' THEN 'S26_I_1.3.2.H.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DK','ZQ','YC','CN','FB')
        AND A.TAG = 'SY'  --省外业务
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.TAG1 = 'DK' THEN 'S26_I_1.3.2.B.2024'
                 WHEN A.TAG1 = 'ZQ' THEN 'S26_I_1.3.2.C.2024'
                 WHEN A.TAG1 = 'FB' THEN 'S26_I_1.3.2.D.2024'
                 WHEN A.TAG1 = 'YC' THEN 'S26_I_1.3.2.G.2024'
                 WHEN A.TAG1 = 'CN' THEN 'S26_I_1.3.2.H.2024'
               END
) q_33
INSERT INTO `S26_I_1.3.2.B.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.3.2.G.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *
INSERT INTO `S26_I_1.3.2.D.2024` (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
SELECT *;

-- 指标: S26_I_1.4.A.2024
--此处依赖S7101报表取数
    INSERT INTO `S26_I_1.4.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.4.A.2024' AS ITEM_NUM,
       SUM(A.LOAN_ACCT_BAL) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_S7101_BAL_TMP1 A --贷款借据信息表
        LEFT JOIN SMTMODS_L_CUST_C B
          ON A.CUST_ID = B.CUST_ID
         AND B.DATA_DATE = I_DATADATE
       WHERE A.DATA_DATE = I_DATADATE
         AND A.CORP_SCALE IN ('S', 'T') --小微企业
         AND A.ITEM_CD NOT LIKE '1301%' ---刨除票据
         AND A.FACILITY_AMT <= 10000000 --单户授信总额1000万元以下，单户授信1000万元（含）以下不含票据融资合计
         AND SUBSTR(NVL(B.REGION_CD,B.ORG_AREA),1,2) <> '22' --去吉林  空值先不取
         AND SUBSTR(B.CUST_TYP,1,1) IN ('0','1')  --企业
         AND CORP_BUSINSESS_TYPE NOT LIKE 'J%' --非金融企业
       GROUP BY A.ORG_NUM;


-- 指标: S26_I_1.7.1.A.2024
INSERT INTO `S26_I_1.7.1.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.7.1.A.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP1_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND TAG1 = 'MYRZ'
       GROUP BY A.ORG_NUM;


-- 指标: S26_I_2_3.1.2.F.2024
INSERT INTO `S26_I_2_3.1.2.F.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT 
      I_DATADATE AS DATA_DATE,
      A.ORG_NUM AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_I' AS REP_NUM,
      'S26_I_2_3.1.2.F.2024' AS ITEM_NUM,
      SUM(NVL(A.SRJE,0) - NVL(D.SRJE,0)) AS ITEM_VAL,
      '2' AS FLAG
       FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       LEFT JOIN CBRC_TMP_ACCT_DEPOSIT_S2601 D
         ON A.ACCT_NUM = D.ACCT_NUM
        AND A.DEPOSIT_NUM = D.DEPOSIT_NUM
        AND D.DATA_DATE = LAST_YEAR
      WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 = 'N' --未设分支机构
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_2.1.1.F.2024
INSERT INTO `S26_I_2.1.1.F.2024`
    (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       CASE
         WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.F.2024'
         WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.F.2024'
         WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.F.2024'
         WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.F.2024'
       END AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP2_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 IN ('DB','YC')
      GROUP BY A.ORG_NUM,
               CASE
                 WHEN A.MATUR_DATE = '1' THEN 'S26_I_2.1.1.F.2024'
                 WHEN A.MATUR_DATE = '2' THEN 'S26_I_2.1.2.F.2024'
                 WHEN A.MATUR_DATE = '3' THEN 'S26_I_2.1.3.F.2024'
                 WHEN A.MATUR_DATE = '4' THEN 'S26_I_2.1.4.F.2024'
               END;


-- 指标: S26_I_2_3.2.3.D.2024
INSERT INTO `S26_I_2_3.2.3.D.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       ITEM_NUM AS ITEM_NUM,
       SUM(ITEM_VAL) AS ITEM_VAL,
       '2' AS FLAG
        FROM (SELECT A.ORG_NUM,
                     A.CUST_ID,
                     CASE
                       WHEN SUM(A.BALANCE) <= 50000000 THEN
                        'S26_I_2_3.2.3.D.2024'
                       WHEN SUM(A.BALANCE) > 50000000 THEN
                        'S26_I_2_3.2.4.D.2024'
                     END ITEM_NUM,
                     SUM(A.BALANCE) ITEM_VAL
                FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
               WHERE A.DATA_DATE = I_DATADATE
                 AND A.GL_ITEM_CODE IN ('20120106', '20120204')
               GROUP BY A.ORG_NUM, A.CUST_ID)
       GROUP BY ORG_NUM, ITEM_NUM;


-- 指标: S26_I_2_3.1.1.F.2024
INSERT INTO `S26_I_2_3.1.1.F.2024`
     (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
     SELECT 
      I_DATADATE AS DATA_DATE,
      A.ORG_NUM AS ORG_NUM,
      'CBRC' AS SYS_NAM,
      'S26_I' AS REP_NUM,
      'S26_I_2_3.1.1.F.2024' AS ITEM_NUM,
      SUM(NVL(A.SRJE,0) - NVL(D.SRJE,0)) AS ITEM_VAL,
      '2' AS FLAG
       FROM CBRC_TMP_ACCT_DEPOSIT_S2601 A
       LEFT JOIN CBRC_TMP_ACCT_DEPOSIT_S2601 D
         ON A.ACCT_NUM = D.ACCT_NUM
        AND A.DEPOSIT_NUM = D.DEPOSIT_NUM
        AND D.DATA_DATE = LAST_YEAR
        AND A.TAG1 = D.TAG1 --设有分支机构
      WHERE A.DATA_DATE = I_DATADATE
        AND A.TAG1 = 'Y' --设有分支机构
      GROUP BY A.ORG_NUM;


-- 指标: S26_I_1.7.2.A.2024
INSERT INTO `S26_I_1.7.2.A.2024`
      (DATA_DATE, ORG_NUM, SYS_NAM, REP_NUM, ITEM_NUM, ITEM_VAL, FLAG)
      SELECT 
       I_DATADATE AS DATA_DATE,
       A.ORG_NUM AS ORG_NUM,
       'CBRC' AS SYS_NAM,
       'S26_I' AS REP_NUM,
       'S26_I_1.7.2.A.2024' AS ITEM_NUM,
       SUM(A.BALANCE) AS ITEM_VAL,
       '2' AS FLAG
        FROM CBRC_TMP1_ACCT_LOAN_S2601 A
       WHERE A.DATA_DATE = I_DATADATE
        AND TAG1 = 'GYL'
       GROUP BY A.ORG_NUM;


