import type { ArkDesktopAgent, ArkDesktopAutomation, ArkDesktopSkill } from './types';

export const DEFAULT_ARK_DESKTOP_SKILLS: ArkDesktopSkill[] = [
    {
        id: 'document-processing',
        name: '文档处理',
        description: '读取、整理、提炼和改写本地文档。',
        instruction: '处理文档时先确认文件路径和输出格式，保留原始事实，不臆造缺失内容；输出修改摘要。',
        category: 'office',
        enabled: true,
        builtIn: true,
    },
    {
        id: 'regulatory-query',
        name: '监管数据查询',
        description: '分析监管指标、表、字段和本地数据材料。',
        instruction: '监管数据任务必须明确监管制度、数据日期、表和字段口径；无法确认时列出待确认项。',
        category: 'data',
        enabled: true,
        builtIn: true,
    },
    {
        id: 'data-analysis',
        name: '数据分析及可视化',
        description: '检查数据质量、完成分析并生成可复用图表。',
        instruction: '数据分析先检查字段、空值、异常值和统计口径，再执行计算；结论必须能追溯到数据证据。',
        category: 'data',
        enabled: true,
        builtIn: true,
    },
    {
        id: 'code-development',
        name: '代码开发',
        description: '理解工程、修改代码、运行测试并总结变更。',
        instruction: '代码任务先检查仓库约束和当前工作区状态，实施最小必要修改，完成后运行与影响范围匹配的测试。',
        category: 'code',
        enabled: true,
        builtIn: true,
    },
    {
        id: 'deep-research',
        name: '深度研究',
        description: '围绕复杂主题收集证据并形成结构化结论。',
        instruction: '研究任务区分事实、推断和待验证内容；引用本地资料时标明文件路径，避免无来源的确定性结论。',
        category: 'research',
        enabled: true,
        builtIn: true,
    },
    {
        id: 'workflow-orchestration',
        name: '技能编排',
        description: '把复杂目标拆成可执行步骤并持续验证。',
        instruction: '复杂任务先列出简短计划和验收条件；每完成一个阶段就验证产物，再继续下一阶段。',
        category: 'workflow',
        enabled: true,
        builtIn: true,
    },
];

export const DEFAULT_ARK_DESKTOP_AGENTS: ArkDesktopAgent[] = [
    {
        id: 'grok-general',
        name: 'Grok 通用执行助手',
        description: '自动分析任务并选择合适技能完成本地工作。',
        systemPrompt: '你是 ARK Desktop 中的本地执行助手。围绕用户目标工作，主动读取工作区、使用工具、生成可验证产物，并清楚汇报实际完成结果。',
        skillIds: ['workflow-orchestration'],
        enabled: true,
        builtIn: true,
    },
    {
        id: 'grok-code',
        name: 'Grok 代码开发助手',
        description: '面向本地代码仓库进行分析、开发、调试和测试。',
        systemPrompt: '你是严谨的本地软件工程 Agent。遵循仓库规则，保护用户已有改动，修改前定位真实调用链，修改后运行测试并报告证据。',
        skillIds: ['code-development', 'workflow-orchestration'],
        enabled: true,
        builtIn: true,
    },
    {
        id: 'grok-data',
        name: 'Grok 数据分析助手',
        description: '处理本地数据、SQL、监管指标和可视化任务。',
        systemPrompt: '你是数据与监管分析 Agent。优先核对数据结构和业务口径，所有结论必须可追溯，生成的 SQL、图表和报告应可复用。',
        skillIds: ['regulatory-query', 'data-analysis'],
        enabled: true,
        builtIn: true,
    },
    {
        id: 'grok-office',
        name: 'Grok 日常办公助手',
        description: '处理文档、总结、方案和研究型工作。',
        systemPrompt: '你是本地办公与研究 Agent。优先使用用户提供的本地文件，保留事实和格式要求，交付可以直接使用的成果。',
        skillIds: ['document-processing', 'deep-research'],
        enabled: true,
        builtIn: true,
    },
];

export const DEFAULT_ARK_DESKTOP_AUTOMATIONS: ArkDesktopAutomation[] = [
    {
        id: 'automation-code-check',
        name: '代码变更检查',
        description: '检查当前工作区未提交变更，定位明显缺陷并输出验证建议。',
        prompt: '检查当前工作区的未提交代码变更，分析可能的缺陷、风险和遗漏测试，给出按优先级排序的结论。',
        agentId: 'grok-code',
        skillIds: ['code-development'],
        schedule: 'manual',
        scheduleTime: '09:00',
        enabled: true,
    },
    {
        id: 'automation-daily-summary',
        name: '工作区日报',
        description: '根据工作区最近变更生成当日工作摘要。',
        prompt: '分析当前工作区最近的代码和文档变更，生成今日工作摘要、风险和下一步建议。',
        agentId: 'grok-general',
        skillIds: ['workflow-orchestration'],
        schedule: 'manual',
        scheduleTime: '18:00',
        enabled: true,
    },
];
