CREATE TABLE IF NOT EXISTS `sys_reg_table` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    `name` VARCHAR(100) COMMENT '名称',
    `cn_name` VARCHAR(100) COMMENT '中文名',
    `system_code` VARCHAR(50) COMMENT '系统编号',
    `subject_code` VARCHAR(50) COMMENT '科目号',
    `subject_name` VARCHAR(100) COMMENT '科目名',
    `theme` VARCHAR(100) COMMENT '主题',
    `frequency` VARCHAR(50) COMMENT '频度',
    `source_type` VARCHAR(50) COMMENT '来源类型',
    `auto_fetch_status` VARCHAR(50) COMMENT '取数状态',
    `document_no` VARCHAR(100) COMMENT '文档编号',
    `document_title` VARCHAR(255) COMMENT '文档标题',
    `effective_date` DATE COMMENT '生效日期',
    `business_caliber` TEXT COMMENT '业务口径',
    `dev_notes` TEXT COMMENT '开发备注',
    `owner` VARCHAR(100) COMMENT '负责人',
    `status` INT DEFAULT 1 COMMENT '状态',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监管报表';

CREATE TABLE IF NOT EXISTS `sys_reg_element` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    `table_id` BIGINT COMMENT '所属表ID',
    `type` VARCHAR(50) COMMENT '类型',
    `name` VARCHAR(100) COMMENT '字段名',
    `cn_name` VARCHAR(100) COMMENT '中文名',
    `code` VARCHAR(100) COMMENT '编码',
    `data_type` VARCHAR(50) COMMENT '数据类型',
    `length` INT COMMENT '长度',
    `is_pk` INT DEFAULT 0 COMMENT '是否主键',
    `nullable` INT DEFAULT 1 COMMENT '是否可空',
    `formula` TEXT COMMENT '公式',
    `fetch_sql` TEXT COMMENT '取数SQL',
    `code_snippet` TEXT COMMENT '代码片段',
    `code_table_code` VARCHAR(100) COMMENT '引用码表',
    `value_range` VARCHAR(255) COMMENT '值域',
    `validation_rule` VARCHAR(255) COMMENT '校验规则',
    `document_no` VARCHAR(100) COMMENT '文档编号',
    `document_title` VARCHAR(255) COMMENT '文档标题',
    `effective_date` DATE COMMENT '生效日期',
    `business_caliber` TEXT COMMENT '业务口径',
    `fill_instruction` TEXT COMMENT '填报说明',
    `dev_notes` TEXT COMMENT '开发备注',
    `auto_fetch_status` VARCHAR(50) COMMENT '取数状态',
    `owner` VARCHAR(100) COMMENT '负责人',
    `status` INT DEFAULT 1 COMMENT '状态',
    `is_init` INT DEFAULT 0 COMMENT '是否初始化',
    `is_merge_formula` INT DEFAULT 0 COMMENT '是否归并',
    `is_fill_business` INT DEFAULT 0 COMMENT '是否填报',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监管元素';

CREATE TABLE IF NOT EXISTS `t_deploy_environment` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `code` VARCHAR(20) NOT NULL,
    `sso_id` BIGINT NOT NULL,
    `deploy_url` VARCHAR(500),
    `deploy_type` VARCHAR(20),
    `config` JSON,
    `created_at` DATETIME,
    `updated_at` DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部署环境';
