DROP PROCEDURE IF EXISTS ExecuteIdempotent_V31;
DELIMITER $$
CREATE PROCEDURE ExecuteIdempotent_V31()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

ALTER TABLE t_ai_knowledge_base 
ADD COLUMN external_url VARCHAR(255) DEFAULT NULL COMMENT 'Dify API Endpoint',
ADD COLUMN external_api_key VARCHAR(255) DEFAULT NULL COMMENT 'Dify API Key';


END$$
DELIMITER ;
CALL ExecuteIdempotent_V31();
DROP PROCEDURE ExecuteIdempotent_V31;
