-- 黄金测试用例 01: 基础 INSERT INTO ... SELECT
-- 场景：直接字段映射，无转换，单源单目标

INSERT INTO DWD.ORDER_FACT
  (ORDER_ID, CUSTOMER_ID, ORDER_DATE, AMOUNT, STATUS)
SELECT
  A.ORDER_ID,
  A.CUSTOMER_ID,
  A.ORDER_DATE,
  A.AMOUNT,
  A.STATUS
FROM ODS.ORDERS A;
