-- 黄金测试用例 02: CASE WHEN 转换 + 常量列
-- 场景：字段经过 CASE WHEN 转换，部分列为常量

INSERT INTO DWD.FTP_DETAIL
  (DATA_DATE, BUSINESS_TYPE, TERM_TYPE, RATE_VALUE, ORG_CODE, BIZ_LINE)
SELECT
  TO_CHAR(TO_DATE(A.AS_OF_DATE, 'YYYYMMDD'), 'YYYY-MM-DD'),
  CASE
    WHEN A.BIZ_TYPE = 'DEPOSIT' THEN 'A'
    WHEN A.BIZ_TYPE = 'LOAN' THEN 'B'
    ELSE 'C'
  END,
  A.TERM_VALUE || A.TERM_UNIT,
  A.RATE_VALUE,
  '019801',
  '99'
FROM ODS.FTP_SOURCE A
WHERE A.AS_OF_DATE = '20210101';
