-- 黄金测试用例 03: JOIN + WHERE 条件（间接流）
-- 场景：多表 JOIN，WHERE 过滤，包含聚合函数

INSERT INTO DWD.CUSTOMER_SUMMARY
  (CUSTOMER_ID, CUSTOMER_NAME, TOTAL_AMOUNT, ORDER_COUNT, LAST_ORDER_DATE)
SELECT
  C.CUSTOMER_ID,
  C.CUSTOMER_NAME,
  SUM(O.AMOUNT) AS TOTAL_AMOUNT,
  COUNT(O.ORDER_ID) AS ORDER_COUNT,
  MAX(O.ORDER_DATE) AS LAST_ORDER_DATE
FROM ODS.CUSTOMERS C
JOIN ODS.ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = 'COMPLETED'
  AND O.ORDER_DATE >= '2021-01-01'
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME;
