-- 黄金测试用例 04: CTE + 子查询嵌套
-- 场景：WITH CTE + 子查询作为源 + 多层嵌套

WITH monthly_stats AS (
  SELECT
    CUSTOMER_ID,
    TO_CHAR(ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,
    SUM(AMOUNT) AS MONTHLY_AMOUNT,
    COUNT(*) AS MONTHLY_COUNT
  FROM ODS.ORDERS
  WHERE STATUS = 'COMPLETED'
  GROUP BY CUSTOMER_ID, TO_CHAR(ORDER_DATE, 'YYYY-MM')
)
INSERT INTO DWD.CUSTOMER_MONTHLY
  (CUSTOMER_ID, ORDER_MONTH, MONTHLY_AMOUNT, MONTHLY_COUNT, CUSTOMER_NAME)
SELECT
  M.CUSTOMER_ID,
  M.ORDER_MONTH,
  M.MONTHLY_AMOUNT,
  M.MONTHLY_COUNT,
  C.CUSTOMER_NAME
FROM monthly_stats M
JOIN ODS.CUSTOMERS C ON M.CUSTOMER_ID = C.CUSTOMER_ID;
