CREATE OR REPLACE PROCEDURE SP_IRS_DK_TZYWYE(IS_DATE    IN VARCHAR2,
                                                OI_RETCODE OUT INTEGER,
                                               OI_RETCODE2 OUT VARCHAR2) AS
  VI_ERRORCODE      NUMBER DEFAULT 0;
  VS_TEXT           VARCHAR2(500) DEFAULT NULL;
  VS_OWNER          VARCHAR2(32) DEFAULT NULL;
  VS_PROCEDURE_NAME VARCHAR2(40) DEFAULT NULL;
  VS_STEP           VARCHAR2(30);
BEGIN
  VS_TEXT := IS_DATE;
  SELECT T.USERNAME INTO VS_OWNER FROM SYS.USER_USERS T;
  VS_PROCEDURE_NAME := 'SP_IRS_DK_TZYWYE';
  VS_STEP := 'START';
  SP_IRS_LOG(VS_PROCEDURE_NAME, VS_STEP, VI_ERRORCODE, VS_TEXT, IS_DATE);

  SP_IRS_PARTITIONS(IS_DATE, 'IE_DK_TZYWYE', OI_RETCODE);

  INSERT INTO IE_DK_TZYWYE
  (DATADATE
  ,CUSTID
  ,CORPID
  ,ACCOUNT
  ,ODBUSITYPE
  ,MONEYSYMB
  ,BALANCE
  ,REALRATE
  ,RATETYPE
  ,PRICINGTYPE
  ,BASERATE
  ,FLOATFREQ
  ,CREDITCARDFLG
  ,CJRQ
  ,NBJGH
  ,BIZ_LINE_ID
  )
  SELECT
   DATADATE
  ,CUSTID
  ,'019803'
  ,ACCOUNT
  ,ODBUSITYPE
  ,MONEYSYMB
  ,BALANCE
  ,REALRATE
  ,RATETYPE
  ,PRICINGTYPE
  ,BASERATE
  ,FLOATFREQ
  ,CREDITCARDFLG
  ,IS_DATE
  ,'019803'
  ,'99'
  FROM IE_DK_TZYWYE1 A;

  COMMIT;

  OI_RETCODE := 0;
  OI_RETCODE2 := 'OK';
  VS_STEP := 'END';
  SP_IRS_LOG(VS_PROCEDURE_NAME, VS_STEP, VI_ERRORCODE, VS_TEXT, IS_DATE);

EXCEPTION
  WHEN OTHERS THEN
    VI_ERRORCODE := SQLCODE;
    VS_TEXT      := VS_STEP || '|' || IS_DATE || '|' || SUBSTR(SQLERRM, 1, 200);
    ROLLBACK;
    OI_RETCODE := -1;
    OI_RETCODE2 := SUBSTR(SQLERRM, 1, 200);
    SP_IRS_LOG(VS_PROCEDURE_NAME, VS_STEP, VI_ERRORCODE, VS_TEXT, IS_DATE);
END;
/
