DROP Procedure IF EXISTS `PROC_BSP_6_27_TMP_SNSX` ;

DELIMITER //

CREATE DEFINER="ybt_datacore"@"%" PROCEDURE "PROC_BSP_6_27_TMP_SNSX"(IN I_DATE VARCHAR(8),
                                         OUT OI_RETCODE   INT, -- 返回CODE
                                         OUT OI_REMESSAGE VARCHAR -- 返回MESSAGE
                                         )
BEGIN

  /******
      程序名称  ：表6.27贷款协议补充信息
      程序功能  ：加工表6.27贷款协议补充信息
      目标表：T_6_27
      源表  ：
      创建人  ：JLF
      创建日期  ：20240119
      版本号：V0.0.1 
  ******/
	
  #声明变量
  DECLARE P_DATE   		DATE;			#数据日期
  DECLARE A_DATE   		VARCHAR(10);    #数据日期
  DECLARE P_PROC_NAME  	VARCHAR(200);	#存储过程名称
  DECLARE P_STATUS  	INT;  			#执行状态
  DECLARE P_START_DT  	DATETIME;		#日志开始日期
  DECLARE P_END_TIME  	DATETIME;		#日志结束日期
  DECLARE P_SQLCDE		VARCHAR(200);	#日志错误代码
  DECLARE P_STATE  		VARCHAR(200);	#日志状态代码
  DECLARE P_SQLMSG		VARCHAR(2000);	#日志详细信息
  DECLARE P_STEP_NO   	INT;			#日志执行步骤
  DECLARE P_DESCB  		VARCHAR(200);	#日志执行步骤描述
  DECLARE BEG_MON_DT 	VARCHAR(8);		#月初
  DECLARE BEG_QUAR_DT 	VARCHAR(8);		#季初
  DECLARE BEG_YEAR_DT 	VARCHAR(8);		#年初
  DECLARE LAST_MON_DT  	VARCHAR(8);		#上月末
  DECLARE LAST_QUAR_DT  VARCHAR(8);		#上季末
  DECLARE LAST_YEAR_DT  VARCHAR(8);		#上年末
  DECLARE LAST_DT  		VARCHAR(8);		#上日
  DECLARE FINISH_FLG    VARCHAR(8);		#完成标志  
  #声明异常
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
   GET DIAGNOSTICS CONDITION 1 P_SQLCDE = GBASE_ERRNO,P_SQLMSG = MESSAGE_TEXT,P_STATE = RETURNED_SQLSTATE;
   SET P_STATUS = -1;
   SET P_START_DT = NOW();
   SET P_STEP_NO = P_STEP_NO + 1;
   SET P_DESCB = '程序异常';
   CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
   SET OI_RETCODE = P_STATUS; 
   SET OI_REMESSAGE = P_DESCB || ':' || P_SQLCDE || ' - ' || P_SQLMSG;
   SELECT OI_RETCODE,'|',OI_REMESSAGE;		
  END;
  
    #变量初始化
	SET P_DATE = TO_DATE(I_DATE,'YYYYMMDD');	
	SET A_DATE = SUBSTR(I_DATE,1,4) || '-' || SUBSTR(I_DATE,5,2) || '-' || SUBSTR(I_DATE,7,2);		
	SET BEG_MON_DT = SUBSTR(I_DATE,1,6) || '01';	
	SET BEG_QUAR_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY') || TRIM(TO_CHAR(QUARTER(TO_DATE(I_DATE,'YYYYMMDD')) * 3 - 2,'00')) || '01'; 
	SET BEG_YEAR_DT = SUBSTR(I_DATE,1,4) || '0101';	
    SET LAST_MON_DT = TO_CHAR(TO_DATE(BEG_MON_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_QUAR_DT = TO_CHAR(TO_DATE(BEG_QUAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_YEAR_DT = TO_CHAR(TO_DATE(BEG_YEAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
	SET LAST_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD') - 1,'YYYYMMDD'); 			
	SET P_PROC_NAME = 'PROC_BSP_6_27_TMP_SNSX';
	SET OI_RETCODE = 0;
	SET P_STATUS = 0;
	SET P_STEP_NO = 0;
	SET OI_RETCODE = 0;
	
    #1.过程开始执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程开始执行'; 
				 
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);								

    #2.清除数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '清除数据';
	
	TRUNCATE  TABLE  SNSX_TEMP1 ;
	
	  									
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
    
    #3.插入数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '插入临时表';
	
	
	-- 涉农授信
	INSERT INTO SNSX_TEMP1 

      SELECT  I_DATE, J.CUST_ID, SUM(J.FACILITY_AMT)
        FROM (SELECT /*+ PARALLEL(4) */
               T.CUST_ID, SUM(T.FACILITY_AMT * TT.CCY_RATE) AS FACILITY_AMT  
                FROM SMTMODS.L_AGRE_CREDITLINE T
                LEFT JOIN SMTMODS.L_PUBL_RATE TT -- 汇率表
                  ON TT.CCY_DATE = TO_DATE(I_DATE, 'YYYYMMDD')
                 AND TT.BASIC_CCY = T.CURR_CD
                 AND TT.FORWARD_CCY = 'CNY'
               INNER JOIN SMTMODS.L_CUST_C C
                  ON T.CUST_ID = C.CUST_ID
                 AND C.DATA_DATE = I_DATE
               WHERE T.DATA_DATE = I_DATE
                 AND T.FACILITY_TYP IN ('2', '4')
               GROUP BY T.CUST_ID 
              ) J
       GROUP BY CUST_ID;
       COMMIT  ;
      
       INSERT INTO SNSX_TEMP1 
     
      SELECT I_DATE AS DATA_DATE,
             C.CUST_ID,
             SUM(C.CONTRACT_AMT * R.CCY_RATE) AS FACILITY_AMT
        FROM SMTMODS.L_AGRE_LOAN_CONTRACT C
       INNER JOIN (SELECT T.ACCT_NUM, SUM(T.LOAN_ACCT_BAL)
                     FROM SMTMODS.L_ACCT_LOAN T
                     LEFT JOIN SMTMODS.L_CUST_P T2
                       ON T.CUST_ID = T2.CUST_ID
                      AND T.DATA_DATE = T2.DATA_DATE
                    WHERE T.DATA_DATE = I_DATE
                      AND (T.ACCT_TYP LIKE '0102%' -- 个人经营性标识
                          OR (SUBSTR(T.ACCT_TYP, 1, 4) = '0199' -- 其他个人贷款
                          AND T.ITEM_CD LIKE '1305%'))
                    GROUP BY T.ACCT_NUM) TT
          ON C.CONTRACT_NUM = TT.ACCT_NUM
        LEFT JOIN SMTMODS.L_PUBL_RATE R -- 汇率表
          ON R.DATA_DATE = C.DATA_DATE
         AND R.BASIC_CCY = C.CURR_CD
         AND R.FORWARD_CCY = 'CNY'
       WHERE C.DATA_DATE = I_DATE
         AND C.ACCT_STS = '1'
        GROUP BY C.CUST_ID;
         COMMIT  ;

     INSERT INTO SNSX_TEMP1
    
      ( DATA_DATE,CUST_ID, FACILITY_AMT)
      SELECT  I_DATE,C.CUST_ID, SUM(C.CONTRACT_AMT * R.CCY_RATE) AS FACILITY_AMT
        FROM SMTMODS.L_AGRE_LOAN_CONTRACT C
       INNER JOIN SMTMODS.L_ACCT_LOAN T1
          ON C.CONTRACT_NUM = T1.ACCT_NUM
         AND C.DATA_DATE = T1.DATA_DATE
        LEFT JOIN SMTMODS.L_PUBL_RATE R -- 汇率表
          ON R.DATA_DATE = C.DATA_DATE
         AND R.BASIC_CCY = C.CURR_CD
         AND R.FORWARD_CCY = 'CNY'
       WHERE C.DATA_DATE = I_DATE
         AND C.ACCT_STS = '1' -- 取有效合同
         AND (T1.ACCT_TYP LIKE '0102%' -- 个人经营性标识
             OR (SUBSTR(T1.ACCT_TYP, 1, 4) = '0199' -- 0199其他个人贷款
             AND T1.ITEM_CD LIKE '1305%'))
         AND NOT EXISTS (SELECT 1
                FROM SNSX_TEMP1 A
               WHERE A.CUST_ID = C.CUST_ID
                 AND A.DATA_DATE = I_DATE) -- 授信表中含公司名个人户，避免个人户统一授信重复
        GROUP BY C.CUST_ID;
	       COMMIT  ;
	       
	       
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);		

    #4.过程结束执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程结束执行';
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
    SET OI_RETCODE = P_STATUS; 
    SET OI_REMESSAGE = P_DESCB;
    SELECT OI_RETCODE,'|',OI_REMESSAGE;
END //

