DROP PROCEDURE IF EXISTS PROC_BSP_T_2_6_KHCWXX;

CREATE PROCEDURE PROC_BSP_T_2_6_KHCWXX(
  IN I_DATE STRING,
  OUT OI_RETCODE INT,
  OUT OI_REMESSAGE STRING
)
LANGUAGE HIVE
BEGIN

  /******
      程序名称  ：客户财务信息
      程序功能  ：加工客户财务信息
      目标表：T_2_6
      发文  ：上报机构的授信客户财务信息，包括单一法人授信客户、集团授信客户。填报银行掌握的该客户最新的财务指标。同业客户、个体工商户不填报本报表
      创建人  ：87V
      创建日期  ：20240109
      版本号：V0.0.1 
  ******/
  -- JLBA202411070004_关于一表通监管数据报送系统修改逻辑的需求 20241212
  -- JLBA202501130010_关于一表通系统实现同业授信客户高管股东等信息自动报送的需求-20250415

  #声明变量
  DECLARE P_DATE DATE;
  DECLARE P_PROC_NAME STRING;
  DECLARE P_STATUS INT;
  DECLARE P_START_DT TIMESTAMP;
  DECLARE P_END_TIME TIMESTAMP;
  DECLARE P_SQLCDE STRING;
  DECLARE P_STATE STRING;
  DECLARE P_SQLMSG STRING;
  DECLARE P_STEP_NO INT;
  DECLARE P_DESCB STRING;
  DECLARE BEG_MON_DT STRING;
  DECLARE BEG_QUAR_DT STRING;
  DECLARE BEG_YEAR_DT STRING;
  DECLARE LAST_MON_DT STRING;
  DECLARE LAST_QUAR_DT STRING;
  DECLARE LAST_YEAR_DT STRING;
  DECLARE LAST_DT STRING;
  DECLARE FINISH_FLG STRING;

  #变量初始化
  SET P_DATE = to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd')));
  SET BEG_MON_DT = date_format(trunc(P_DATE,'MM'),'yyyyMMdd');
  SET BEG_QUAR_DT = date_format(trunc(P_DATE,'Q'),'yyyyMMdd');
  SET BEG_YEAR_DT = date_format(trunc(P_DATE,'YY'),'yyyyMMdd');
  SET LAST_MON_DT = date_format(date_sub(trunc(P_DATE,'MM'),1),'yyyyMMdd');
  SET LAST_QUAR_DT = date_format(date_sub(trunc(P_DATE,'Q'),1),'yyyyMMdd');
  SET LAST_YEAR_DT = date_format(date_sub(trunc(P_DATE,'YY'),1),'yyyyMMdd');
  SET LAST_DT = date_format(date_sub(P_DATE,1),'yyyyMMdd');
  SET P_PROC_NAME = 'PROC_BSP_T_2_6_KHCWXX';
  SET OI_RETCODE = 0;
  SET P_STATUS = 0;
  SET P_STEP_NO = 0;

  #1.过程开始执行
  SET P_START_DT = current_timestamp();
  SET P_STEP_NO = P_STEP_NO + 1;
  SET P_DESCB = '过程开始执行';
  CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,current_timestamp(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);

  #2.清除数据
  SET P_START_DT = current_timestamp();
  SET P_STEP_NO = P_STEP_NO + 1;
  SET P_DESCB = '清除数据';
  TRUNCATE TABLE T_2_6;
  CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,current_timestamp(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);

  DROP TEMPORARY TABLE IF EXISTS CUST_TAB_2_6;
  CREATE TEMPORARY TABLE CUST_TAB_2_6 AS
  (
    SELECT B010001 AS CUST_ID FROM T_2_1 WHERE DIS_DATA_DATE = date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd')
    UNION ALL 
    SELECT B020001 AS CUST_ID FROM T_2_2 WHERE DIS_DATA_DATE = date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd')
    UNION ALL 
    SELECT B030001 AS CUST_ID FROM T_2_3 WHERE DIS_DATA_DATE = date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd')
  );

  #3.插入数据
  SET P_START_DT = current_timestamp();
  SET P_STEP_NO = P_STEP_NO + 1;
  SET P_DESCB = '数据插入';

  INSERT INTO T_2_6 (
    B060001, B060002, B060003, B060004, B060005, B060006, B060007, B060008, B060009, B060010,
    B060011, B060012, B060013, B060014, B060015, B060016, B060017, B060018, B060019, B060020,
    B060021, B060022, DIS_DATA_DATE, DIS_BANK_ID, DEPARTMENT_ID
  )
  SELECT
    T1.CUST_ID AS KHTYBH,
    ORG.ORG_ID AS NBJGH,
    coalesce(T3.CUST_NAM,T2.CUST_NAM) AS KHMC,
    CASE 
      WHEN T1.REPORT_TYP = '10' THEN concat(T1.REPORT_YEAR,'-12-31')
      WHEN T1.REPORT_TYP = '20' THEN concat(T1.REPORT_YEAR,'-06-30')
      WHEN T1.REPORT_TYP = '30' THEN concat(T1.REPORT_YEAR,'-12-31')
      WHEN T1.REPORT_TYP = '40' THEN concat(T1.REPORT_YEAR,'-03-31')
      WHEN T1.REPORT_TYP = '50' THEN concat(T1.REPORT_YEAR,'-06-30')
      WHEN T1.REPORT_TYP = '60' THEN concat(T1.REPORT_YEAR,'-09-30')
      WHEN T1.REPORT_TYP = '70' THEN concat(T1.REPORT_YEAR,'-12-31')
    END AS B060004,
    CASE WHEN T1.AUDIT_FLAG = 'N' THEN '0' WHEN T1.AUDIT_FLAG = 'Y' THEN '1' END AS SFSJ,
    T1.AUDIT_OFFICE_NAM AS SJJG,
    CASE 
      WHEN T1.REPORT_SUB_TYP = '1' THEN '01'
      WHEN T1.REPORT_SUB_TYP = '2' THEN '02'
      WHEN T1.REPORT_SUB_TYP = '9' THEN '00'
    END AS BBKJ,
    T1.CURR_CD AS BZ,
    SUM(coalesce(T1.ID_VAL1,0)) AS ZCZE,
    SUM(coalesce(T1.ID_VAL2,0)) AS FZZE,
    SUM(coalesce(T1.ID_VAL4,0)) AS SDS,
    SUM(coalesce(T1.ID_VAL5,0)) AS JLR,
    SUM(coalesce(T1.ID_VAL6,0)) AS ZYYWSR,
    SUM(coalesce(T1.ID_VAL12,0)) AS ZYYWSR,
    SUM(coalesce(T1.ID_VAL7,0)) AS XJLLJE,
    SUM(coalesce(T1.ID_VAL8,0)) AS YSZK,
    SUM(coalesce(T1.ID_VAL9,0)) AS QTYSK,
    SUM(coalesce(T1.ID_VAL10,0)) AS LDZCHJ,
    ABS(SUM(coalesce(T1.ID_VAL11,0))) AS LDFZHJ,
    CASE 
      WHEN T1.REPORT_TYP = '90' THEN '01'
      WHEN T1.REPORT_TYP = '80' THEN '02'
      WHEN T1.REPORT_TYP IN ('40','50','60','70') THEN '03'
      WHEN T1.REPORT_TYP IN ('20','30') THEN '04'
      WHEN T1.REPORT_TYP = '10' THEN '05'
      ELSE '00'
    END AS BBZQ,
    T1.REPORT_KIND AS REPORT_KIND,
    date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd') AS CJRQ,
    date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd') AS ZRRQ,
    T3.ORG_NUM,
    ''
  FROM (
    SELECT 
      A.ORG_NUM, A.CUST_ID, A.REPORT_DT,
      MAX(A.AUDIT_FLAG) AS AUDIT_FLAG,
      concat(A.REPORT_SUB_TYP,A.CUST_ID,A.ORG_NUM,A.REPORT_TYP,A.REPORT_DT) AS REPORT_KIND,
      MAX(A.AUDIT_DT) AS AUDIT_DT,
      MAX(A.AUDIT_OFFICE_NAM) AS AUDIT_OFFICE_NAM,
      MAX(A.REPORT_SUB_TYP) AS REPORT_SUB_TYP,
      MAX(A.CURR_CD) AS CURR_CD,
      MAX(A.REPORT_YEAR) AS REPORT_YEAR,
      SUM(CASE WHEN A.ID_CODE IN ('9587','9130') THEN A.ID_VAL END) AS ID_VAL1,
      SUM(CASE WHEN A.ID_CODE IN ('9635','9152') THEN A.ID_VAL END) AS ID_VAL2,
      SUM(CASE WHEN A.ID_CODE IN ('9747','9184') THEN A.ID_VAL END) AS ID_VAL3,
      SUM(CASE WHEN A.ID_CODE IN ('9749','9185') THEN A.ID_VAL END) AS ID_VAL4,
      SUM(CASE WHEN A.ID_CODE IN ('9755','9186') THEN A.ID_VAL END) AS ID_VAL5,
      SUM(CASE WHEN A.ID_CODE IN ('9675','9189') THEN A.ID_VAL END) AS ID_VAL6,
      SUM(CASE WHEN A.ID_CODE IN ('9855','9231','9233') THEN A.ID_VAL END) AS ID_VAL7,
      SUM(CASE WHEN A.ID_CODE IN ('9103') THEN A.ID_VAL END) AS ID_VAL8,
      SUM(CASE WHEN A.ID_CODE IN ('9107') THEN A.ID_VAL END) AS ID_VAL9,
      SUM(CASE WHEN A.ID_CODE IN ('9111') THEN A.ID_VAL END) AS ID_VAL10,
      SUM(CASE WHEN A.ID_CODE IN ('9143') THEN A.ID_VAL END) AS ID_VAL11,
      SUM(CASE WHEN A.ID_CODE IN ('9108') THEN A.ID_VAL END) AS ID_VAL12,
      MAX(A.REPORT_TYP) AS REPORT_TYP,
      MAX(A.DEPARTMENTD) AS DEPARTMENTD
    FROM (
      SELECT A.* 
      FROM (
        SELECT M.*,
               row_number() OVER (PARTITION BY M.CUST_ID,M.REPORT_TYP,M.ID_CODE,M.REPORT_SUB_TYP ORDER BY M.REPORT_YEAR DESC,M.REPORT_DT DESC) AS RN 
        FROM SMTMODS.L_CUST_C_FINREPINFO M
        INNER JOIN (
          SELECT B.CUST_ID, B.ORG_NUM, B.ID_CODE, MAX(B.REPORT_YEAR) AS REPORT_YEAR
          FROM SMTMODS.L_CUST_C_FINREPINFO B 
          WHERE DATA_DATE = I_DATE
            AND REPORT_KIND NOT IN ('1','2','3','7','8')
            AND B.CUST_ID IN (SELECT DISTINCT CUST_ID FROM CUST_TAB_2_6)
          GROUP BY B.CUST_ID, B.ORG_NUM, B.ID_CODE
        ) F
          ON M.CUST_ID = F.CUST_ID
         AND M.ID_CODE = F.ID_CODE
         AND M.REPORT_YEAR = F.REPORT_YEAR
         AND M.ORG_NUM = F.ORG_NUM
        WHERE DATA_DATE = I_DATE
          AND REPORT_KIND NOT IN ('1','2','3','7','8')
      ) A 
      WHERE RN = 1
    ) A
    GROUP BY A.ORG_NUM, A.CUST_ID, A.REPORT_DT, A.REPORT_YEAR, A.REPORT_SUB_TYP, A.REPORT_TYP
  ) T1
  INNER JOIN SMTMODS.L_CUST_ALL T2
    ON T1.CUST_ID = T2.CUST_ID AND T2.DATA_DATE = I_DATE
  INNER JOIN SMTMODS.L_CUST_C T3
    ON T1.CUST_ID = T3.CUST_ID AND T3.DATA_DATE = I_DATE
  LEFT JOIN VIEW_L_PUBL_ORG_BRA ORG
    ON T3.ORG_NUM = ORG.ORG_NUM AND ORG.DATA_DATE = I_DATE
  LEFT JOIN SMTMODS.L_CUST_C_GROUP_MEM T8
    ON T8.GROUP_MEM_NO = T2.CUST_ID AND T8.GROUP_FLAG = 'Y' AND T8.DATA_DATE = I_DATE
  LEFT JOIN SMTMODS.L_AGRE_CREDITLINE T6
    ON T8.CUST_GROUP_NO = T6.CUST_ID AND T6.DATA_DATE = I_DATE AND T6.FACILITY_STS = 'Y'
  LEFT JOIN SMTMODS.L_AGRE_CREDITLINE T5
    ON T1.CUST_ID = T5.CUST_ID AND T5.DATA_DATE = I_DATE AND T5.FACILITY_STS = 'Y'
  WHERE (T5.CUST_ID IS NOT NULL OR T6.CUST_ID IS NOT NULL)
    AND T2.INLANDORRSHORE_FLG <> 'N'
    AND T2.CUST_TYPE NOT IN ('12')
    AND T3.CUST_TYP NOT IN ('3')
  GROUP BY ORG.ORG_ID, T1.CUST_ID, coalesce(T3.CUST_NAM,T2.CUST_NAM), T1.REPORT_YEAR, T1.AUDIT_OFFICE_NAM,
           T1.CURR_CD, T1.REPORT_TYP, T3.TOTAL_ASSET, T3.TOTAL_DEBT, T3.IN_STOCK, T3.ORG_NUM,
           CASE WHEN T1.AUDIT_FLAG = 'N' THEN '0' WHEN T1.AUDIT_FLAG = 'Y' THEN '1' END,
           CASE WHEN T1.REPORT_SUB_TYP = '1' THEN '01' WHEN T1.REPORT_SUB_TYP = '2' THEN '02' WHEN T1.REPORT_SUB_TYP = '9' THEN '00' END,
           CASE WHEN T1.REPORT_TYP = '90' THEN '01' WHEN T1.REPORT_TYP = '80' THEN '02' 
                WHEN T1.REPORT_TYP IN ('40','50','60','70') THEN '03' WHEN T1.REPORT_TYP IN ('20','30') THEN '04'
                WHEN T1.REPORT_TYP = '10' THEN '05' ELSE '00' END,
           T1.REPORT_KIND,
           date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd'),
           date_format(to_date(from_unixtime(unix_timestamp(I_DATE,'yyyyMMdd'))),'yyyy-MM-dd'),
           T3.ORG_NUM;

  CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,current_timestamp(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);

  #4.过程结束执行
  SET P_START_DT = current_timestamp();
  SET P_STEP_NO = P_STEP_NO + 1;
  SET P_DESCB = '过程结束执行';
  CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,current_timestamp(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
  SET OI_RETCODE = P_STATUS;
  SET OI_REMESSAGE = P_DESCB;
  SELECT OI_RETCODE,'|',OI_REMESSAGE;

EXCEPTION
  WHEN ANY THEN
    SET P_SQLCDE = cast(SQLCODE AS STRING);
    SET P_STATE = SQLSTATE;
    SET P_SQLMSG = SQLERRM;
    SET P_STATUS = -1;
    SET P_START_DT = current_timestamp();
    SET P_STEP_NO = P_STEP_NO + 1;
    SET P_DESCB = '程序异常';
    CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,current_timestamp(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
    SET OI_RETCODE = P_STATUS;
    SET OI_REMESSAGE = concat(P_DESCB, ':', P_SQLCDE, ' - ', P_SQLMSG);
    SELECT OI_RETCODE,'|',OI_REMESSAGE;
END;

