DROP Procedure IF EXISTS `PROC_BSP_T_3_8_JYYDJDYGX` ;

DELIMITER $$

CREATE DEFINER="ybt_datacore"@"%" PROCEDURE "PROC_BSP_T_3_8_JYYDJDYGX"(IN I_DATE VARCHAR(8),
                                        OUT OI_RETCODE   INT,-- 返回code
                                        OUT OI_REMESSAGE VARCHAR -- 返回message
)
BEGIN
/******
      程序名称  ：交易与单据对应关系
      程序功能  ：加工交易与单据对应关系
      目标表：T_3_8
      源表  ：
      创建人  ：LZ
      创建日期  ：20240109
      版本号：V0.0.1 
  ******/
	-- JLBA202411070004_ 20241212
	 /*需求编号：JLBA202507090010 上线日期：2025-08-07，修改人：巴启威，提出人：吴大为  修改原因：关于一表通监管数据报送系统调整失效数据保留时间的需求*/
  #声明变量
  DECLARE P_DATE   		DATE;			#数据日期
  DECLARE P_PROC_NAME  	VARCHAR(200);	#存储过程名称
  DECLARE P_STATUS  	INT;  			#执行状态
  DECLARE P_START_DT  	DATETIME;		#日志开始日期
  DECLARE P_END_TIME  	DATETIME;		#日志结束日期
  DECLARE P_SQLCDE		VARCHAR(200);	#日志错误代码
  DECLARE P_STATE  		VARCHAR(200);	#日志状态代码
  DECLARE P_SQLMSG		VARCHAR(2000);	#日志详细信息
  DECLARE P_STEP_NO   	INT;			#日志执行步骤
  DECLARE P_DESCB  		VARCHAR(200);	#日志执行步骤描述
  DECLARE BEG_MON_DT 	VARCHAR(8);		#月初
  DECLARE BEG_QUAR_DT 	VARCHAR(8);		#季初
  DECLARE BEG_YEAR_DT 	VARCHAR(8);		#年初
  DECLARE LAST_MON_DT  	VARCHAR(8);		#上月末
  DECLARE LAST_QUAR_DT  VARCHAR(8);		#上季末
  DECLARE LAST_YEAR_DT  VARCHAR(8);		#上年末
  DECLARE LAST_DT  		VARCHAR(8);		#上日
  DECLARE FINISH_FLG    VARCHAR(8);		#完成标志  
  #声明异常
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
   GET DIAGNOSTICS CONDITION 1 P_SQLCDE = GBASE_ERRNO,P_SQLMSG = MESSAGE_TEXT,P_STATE = RETURNED_SQLSTATE;
   SET P_STATUS = -1;
   SET P_START_DT = NOW();
   SET P_STEP_NO = P_STEP_NO + 1;
   SET P_DESCB = '程序异常';
   CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
   SET OI_RETCODE = P_STATUS; 
   SET OI_REMESSAGE = P_DESCB || ':' || P_SQLCDE || ' - ' || P_SQLMSG;
   select OI_RETCODE,'|',OI_REMESSAGE;
  END;
  
    #变量初始化
	SET P_DATE = TO_DATE(I_DATE,'YYYYMMDD');		
	SET BEG_MON_DT = SUBSTR(I_DATE,1,6) || '01';	
	SET BEG_QUAR_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY') || TRIM(TO_CHAR(QUARTER(TO_DATE(I_DATE,'YYYYMMDD')) * 3 - 2,'00')) || '01'; 
	SET BEG_YEAR_DT = SUBSTR(I_DATE,1,4) || '0101';	
    SET LAST_MON_DT = TO_CHAR(TO_DATE(BEG_MON_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_QUAR_DT = TO_CHAR(TO_DATE(BEG_QUAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_YEAR_DT = TO_CHAR(TO_DATE(BEG_YEAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
	SET LAST_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD') - 1,'YYYYMMDD'); 			
	SET P_PROC_NAME = 'PROC_BSP_T_3_8_JYYDJDYGX';
	SET OI_RETCODE = 0;
	SET P_STATUS = 0;
	SET P_STEP_NO = 0;
	
    #1.过程开始执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程开始执行';
				 
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);								

    #2.清除数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '清除数据';
	
	DELETE FROM VOUCHER_NUMBER_NUM ;
	COMMIT;
    DELETE FROM CONTRACT_NUM_NUM ;
	COMMIT;
	
	
	DELETE FROM ybt_datacore.T_3_8 WHERE C080007 = to_char(P_DATE,'yyyy-mm-dd');
	
	COMMIT;
   														
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
    
    #3.插入数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '数据插入';
/*
01-打包贷款
02-押汇
03-保理
04-议付信用证
05-买方信贷
06-卖方信贷
07-福费廷
08-承兑汇票
09-保函
10-信用证
00-其他
描述交易与单据对应关系该对应的业务种类。
 */
	
	
INSERT INTO VOUCHER_NUMBER_NUM  
SELECT COUNT(NUM) NUM ,VOUCHER_NUMBER  FROM  
 (SELECT 
  T.ACCT_NUM  AS  CONTRACT_NUM,
  T.LOAN_NUM  AS VOUCHER_NUMBER,
  ROW_NUMBER() OVER(PARTITION BY T.LOAN_NUM ORDER BY T.ACCT_NUM DESC)  AS NUM
FROM SMTMODS.L_ACCT_TRAD_FIN T -- 贸易融资补充信息 
WHERE  T.DATA_DATE = I_DATE 
) J
GROUP BY VOUCHER_NUMBER;
COMMIT;
 
INSERT INTO CONTRACT_NUM_NUM  
SELECT COUNT(NUM) NUM ,CONTRACT_NUM  FROM  
 (SELECT 
  T.ACCT_NUM  AS  CONTRACT_NUM,
  T.LOAN_NUM  AS VOUCHER_NUMBER,
  ROW_NUMBER() OVER(PARTITION BY T.LOAN_NUM ORDER BY T.ACCT_NUM DESC)  AS NUM
FROM SMTMODS.L_ACCT_TRAD_FIN T -- 贸易融资补充信息 
WHERE  T.DATA_DATE = I_DATE
 ) L
GROUP BY CONTRACT_NUM;
COMMIT;
	
	
  INSERT  INTO ybt_datacore.T_3_8  (
    -- C080001, -- 01.交易
    C080002, -- 02.协议
    C080003, -- 03.单据
    C080004, -- 04.交易机构
    C080005, -- 05.对应关系
    C080008, -- 08.业务种类
    C080006, -- 06.备注
    C080007,  -- 07.采集日期
    DIS_DATA_DATE,
    DIS_BANK_ID,
    DEPARTMENT_ID   
)  


SELECT 
 -- A.LOAN_NUM, -- 01 交易ID
 -- T.CONTRACT_NUM 
 A.ACCT_NUM, -- 02 协议ID
 -- T.VOUCHER_NUMBER||A.ACCT_NUM
case when T.VOUCHER_NUMBER is null then 
(CASE WHEN  REGEXP_LIKE( A.LOAN_NUM ,'^[0-9]+$')  ='1' THEN 'JLBS'||A.LOAN_NUM
 ELSE A.LOAN_NUM
 end)
 else T.VOUCHER_NUMBER 
 end AS LOAN_NUM, -- 01 单据ID 
 SUBSTR(TRIM(nvl(B.FIN_LIN_NUM,'B0302H222010001')),1,11)||T.ORG_NUM , -- 04 交易机构ID 
 CASE  
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '01'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '02'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '03'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '04'
       END ,  -- 05 对应关系
case 
  when t.BUSINESS_TYPE = '01' then '08' -- 承兑汇票
  when t.BUSINESS_TYPE = '02' then '09' -- 保函
  when t.BUSINESS_TYPE = '03' then '10' -- 信用证
  when t.BUSINESS_TYPE = '04' then '01' -- 打包贷款
  when t.BUSINESS_TYPE = '05' then '02' -- 押汇
  when t.BUSINESS_TYPE = '06' then '04' -- 议付信用证
  when t.BUSINESS_TYPE = '07' then '05' -- 买方信贷
  when t.BUSINESS_TYPE = '08' then '06' -- 卖方信贷
  when t.BUSINESS_TYPE = '09' then '07' -- 福费廷 
  when t.BUSINESS_TYPE = '10' then '06' -- 08 
  else '00'
  END , -- 06 业务种类
 '00' , -- 07 备注
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 A.ORG_NUM,
 '0098GJ'
FROM SMTMODS.L_TRANS_BACK_INFO T -- 交易背景信息表
INNER JOIN SMTMODS.L_ACCT_TRAD_FIN A -- 贸易融资补充信息 
ON T.CONTRACT_NUM = A.LOAN_NUM  -- 保函的业务编号关联贸易融资的借据号
AND T.DATA_DATE = A.DATA_DATE
INNER JOIN VIEW_L_PUBL_ORG_BRA B -- 机构表
ON T.ORG_NUM = B.ORG_NUM
AND B.DATA_DATE = I_DATE
LEFT JOIN VOUCHER_NUMBER_NUM J
ON A.LOAN_NUM=J.VOUCHER_NUMBER
LEFT JOIN CONTRACT_NUM_NUM L
ON A.ACCT_NUM = L.CONTRACT_NUM
WHERE T.DATA_DATE = I_DATE
AND T.BUSINESS_TYPE = '02'  
-- [20250807][巴启威][JLBA202507090010][吴大为]: 关于一表通监管数据报送系统调整失效数据保留时间的需求
AND SUBSTR(T.COLL_DATE,1,4)= SUBSTR(I_DATE,1,4);
-- AND SUBSTR(T.COLL_DATE,1,6)= SUBSTR(I_DATE,1,6);
-- AND  T.COLL_DATE =  I_DATE ;

    
    COMMIT;

INSERT  INTO ybt_datacore.T_3_8  (
    -- C080001, -- 01.交易
    C080002, -- 02.协议
    C080003, -- 03.单据
    C080004, -- 04.交易机构
    C080005, -- 05.对应关系
    C080008, -- 08.业务种类
    C080006, -- 06.备注
    C080007,  -- 07.采集日期
    DIS_DATA_DATE,
    DIS_BANK_ID,
    DEPARTMENT_ID  
)  
SELECT 
 -- A.LOAN_NUM , -- 01 交易ID
 -- T.CONTRACT_NUM 
 A.ACCT_NUM, -- 02 协议ID
 -- T.VOUCHER_NUMBER||A.ACCT_NUM
  case when T.VOUCHER_NUMBER is null then 
(CASE WHEN  REGEXP_LIKE( A.LOAN_NUM ,'^[0-9]+$')  ='1' THEN 'JLBS'||A.LOAN_NUM
 ELSE A.LOAN_NUM
 end)
 else T.VOUCHER_NUMBER  || T.CONTRACT_NUM  -- JLBA202411070004 YBT_JYJ04-4 20241212
 end AS LOAN_NUM, -- 01 单据ID   
 SUBSTR(TRIM(nvl(B.FIN_LIN_NUM,'B0302H222010001')),1,11)||T.ORG_NUM , -- 04 交易机构ID 
 CASE  
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '01'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '02'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '03'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '04'
       END ,  -- 05 对应关系
case 
  when t.BUSINESS_TYPE = '01' then '08' -- 承兑汇票
  when t.BUSINESS_TYPE = '02' then '09' -- 保函
  when t.BUSINESS_TYPE = '03' then '10' -- 信用证
  when t.BUSINESS_TYPE = '04' then '01' -- 打包贷款
  when t.BUSINESS_TYPE = '05' then '02' -- 押汇
  when t.BUSINESS_TYPE = '06' then '04' -- 议付信用证
  when t.BUSINESS_TYPE = '07' then '05' -- 买方信贷
  when t.BUSINESS_TYPE = '08' then '06' -- 卖方信贷
  when t.BUSINESS_TYPE = '09' then '07' -- 福费廷 
  when t.BUSINESS_TYPE = '10' then '06' -- 08 
  else '00'
  END , -- 06 业务种类
  '01' , -- 07 备注
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 A.ORG_NUM,
 '0098GJ'
FROM SMTMODS.L_TRANS_BACK_INFO T -- 交易背景信息表
INNER JOIN SMTMODS.L_ACCT_TRAD_FIN A -- 贸易融资补充信息 
ON  T.CONTRACT_NUM = A.LETT_CODE  -- 交易背景的信用证的业务编号关联贸易融资的信用证编号
AND T.DATA_DATE = A.DATA_DATE
INNER JOIN VIEW_L_PUBL_ORG_BRA B -- 机构表
ON T.ORG_NUM = B.ORG_NUM
AND B.DATA_DATE = I_DATE
LEFT JOIN VOUCHER_NUMBER_NUM J
ON A.LOAN_NUM=J.VOUCHER_NUMBER
LEFT JOIN CONTRACT_NUM_NUM L
ON A.ACCT_NUM = L.CONTRACT_NUM
WHERE T.DATA_DATE = I_DATE
AND T.BUSINESS_TYPE = '03' 
-- AND  T.COLL_DATE =  I_DATE ;
-- [20250807][巴启威][JLBA202507090010][吴大为]: 关于一表通监管数据报送系统调整失效数据保留时间的需求
AND SUBSTR(T.COLL_DATE,1,4)= SUBSTR(I_DATE,1,4);
-- AND SUBSTR(T.COLL_DATE,1,6)= SUBSTR(I_DATE,1,6);

    COMMIT;
  
INSERT  INTO ybt_datacore.T_3_8  (
    -- C080001, -- 01.交易
    C080002, -- 02.协议
    C080003, -- 03.单据
    C080004, -- 04.交易机构
    C080005, -- 05.对应关系
    C080008, -- 08.业务种类
    C080006, -- 06.备注
    C080007,  -- 07.采集日期
    DIS_DATA_DATE,
    DIS_BANK_ID,
    DEPARTMENT_ID  
)      
    
SELECT
 -- A.LOAN_NUM , -- 01 交易ID
 -- T.CONTRACT_NUM 
 A.ACCT_NUM, -- 02 协议ID
 -- T.VOUCHER_NUMBER||A.ACCT_NUM
 case when T.VOUCHER_NUMBER is null then 
(CASE WHEN  REGEXP_LIKE( A.LOAN_NUM ,'^[0-9]+$')  ='1' THEN 'JLBS'||A.LOAN_NUM
 ELSE A.LOAN_NUM
 end)
 else T.VOUCHER_NUMBER || A.LOAN_NUM
 end AS LOAN_NUM, -- 01 单据ID 
 SUBSTR(TRIM(nvl(C.FIN_LIN_NUM,'B0302H222010001')),1,11)||T.ORG_NUM , -- 04 交易机构ID 
 CASE  
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '01'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '02'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '03'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '04'
       END ,  -- 05 对应关系
'03' , -- 06 业务种类
'02' , -- 07 备注
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 A.ORG_NUM,
 '0098GJ' FROM 
SMTMODS.L_TRANS_BACK_INFO T -- 交易背景信息表
INNER JOIN SMTMODS.L_ACCT_TRAD_FIN A -- 贸易融资补充信息 
ON  T.CONTRACT_NUM = A.ACCT_NUM   -- 交易背景的信用证的业务编号关联贸易融资的信用证编号
AND T.DATA_DATE = A.DATA_DATE  
INNER JOIN VIEW_L_PUBL_ORG_BRA C -- 机构表
ON T.ORG_NUM = C.ORG_NUM
AND C.DATA_DATE = I_DATE
LEFT JOIN VOUCHER_NUMBER_NUM J
ON A.LOAN_NUM=J.VOUCHER_NUMBER
LEFT JOIN CONTRACT_NUM_NUM L
ON A.ACCT_NUM = L.CONTRACT_NUM
WHERE T.DATA_DATE = I_DATE
AND T.BUSINESS_TYPE = '00' 
-- AND  T.COLL_DATE =  I_DATE ;
-- [20250807][巴启威][JLBA202507090010][吴大为]: 关于一表通监管数据报送系统调整失效数据保留时间的需求
AND SUBSTR(T.COLL_DATE,1,4)= SUBSTR(I_DATE,1,4);
-- AND SUBSTR(T.COLL_DATE,1,6)= SUBSTR(I_DATE,1,6);

COMMIT ;
    
    
    
    
    
INSERT  INTO ybt_datacore.T_3_8  (
    -- C080001, -- 01.交易
    C080002, -- 02.协议
    C080003, -- 03.单据
    C080004, -- 04.交易机构
    C080005, -- 05.对应关系
    C080008, -- 08.业务种类
    C080006, -- 06.备注
    C080007,  -- 07.采集日期
    DIS_DATA_DATE,
    DIS_BANK_ID,
    DEPARTMENT_ID  
)      
    
  SELECT 
 -- A.LOAN_NUM , -- 01 交易ID
 -- T.CONTRACT_NUM 
 A.ACCT_NUM, -- 02 协议ID
 -- T.VOUCHER_NUMBER||A.ACCT_NUM
 case when T.VOUCHER_NUMBER is null then 
(CASE WHEN  REGEXP_LIKE( A.LOAN_NUM ,'^[0-9]+$')  ='1' THEN 'JLBS'||A.LOAN_NUM
 ELSE A.LOAN_NUM
 end)
 else T.VOUCHER_NUMBER || A.LOAN_NUM
 end AS LOAN_NUM, -- 01 单据ID 
 SUBSTR(TRIM(nvl(C.FIN_LIN_NUM,'B0302H222010001') ),1,11)||T.ORG_NUM , -- 04 交易机构ID 
 CASE  
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '01'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) = 1 THEN '02'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) = 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '03'
 WHEN NVL(J.VOUCHER_NUMBER_NUM,1) > 1 AND NVL(L.CONTRACT_NUM_NUM,1) > 1 THEN '04'
       END ,  -- 05 对应关系
'03', -- 06 业务种类
'04' , -- 07 备注
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
 A.ORG_NUM,
 '0098GJ'
FROM SMTMODS.L_TRANS_BACK_INFO T -- 交易背景信息表
INNER JOIN SMTMODS.L_ACCT_LOAN B
ON T.CONTRACT_NUM = B.ACCT_NUM
AND B.DATA_DATE = I_DATE
INNER JOIN SMTMODS.L_ACCT_TRAD_FIN A -- 贸易融资补充信息 
ON B.LOAN_NUM = A.LOAN_NUM    -- 交易背景的信用证的业务编号关联贸易融资的信用证编号
AND T.DATA_DATE = A.DATA_DATE 
INNER JOIN VIEW_L_PUBL_ORG_BRA C -- 机构表
ON T.ORG_NUM = C.ORG_NUM
AND C.DATA_DATE = I_DATE
LEFT JOIN VOUCHER_NUMBER_NUM J
ON A.LOAN_NUM=J.VOUCHER_NUMBER
LEFT JOIN CONTRACT_NUM_NUM L
ON A.ACCT_NUM = L.CONTRACT_NUM
WHERE T.DATA_DATE = I_DATE
AND T.BUSINESS_TYPE = '00' -- 保理
-- AND T.COLL_DATE = I_DATE
-- [20250807][巴启威][JLBA202507090010][吴大为]: 关于一表通监管数据报送系统调整失效数据保留时间的需求
AND SUBSTR(T.COLL_DATE,1,4)= SUBSTR(I_DATE,1,4)
-- AND SUBSTR(T.COLL_DATE,1,6)= SUBSTR(I_DATE,1,6)
AND NOT EXISTS (
SELECT 1 FROM 
SMTMODS.L_TRANS_BACK_INFO C -- 交易背景信息表
INNER JOIN SMTMODS.L_ACCT_TRAD_FIN D -- 贸易融资补充信息 
ON  C.CONTRACT_NUM = D.ACCT_NUM   -- 交易背景的信用证的业务编号关联贸易融资的信用证编号
AND C.DATA_DATE = D.DATA_DATE  
WHERE C.DATA_DATE = I_DATE
AND C.BUSINESS_TYPE = '00' 
AND T.CONTRACT_NUM = C.CONTRACT_NUM
)-- 保理  
 ;
 COMMIT ;
    
    
    
    
	
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);		

    #4.过程结束执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程结束执行';
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
   SET OI_RETCODE = P_STATUS; 
   SET OI_REMESSAGE = P_DESCB;
   select OI_RETCODE,'|',OI_REMESSAGE;

END $$


