DROP Procedure IF EXISTS `PROC_BSP_T_4_2_KMXX` ;

DELIMITER $$

CREATE DEFINER="ybt_datacore"@"%" PROCEDURE "PROC_BSP_T_4_2_KMXX"(IN I_DATE VARCHAR(8),
                                        OUT OI_RETCODE   INT,-- 返回CODE
                                        OUT OI_REMESSAGE VARCHAR -- 返回MESSAGE
)
BEGIN

  /******
      程序名称  ：科目信息
      程序功能  ：加工科目信息
      目标表：T_4_2
      源表  ：
      创建人  ：87V
      创建日期  ：20240109
      版本号：V0.0.1 
  ******/
	  -- JLBA202411070004_关于一表通监管数据报送系统修改逻辑的需求
  #声明变量
  DECLARE P_DATE   		DATE;			#数据日期
  DECLARE P_PROC_NAME  	VARCHAR(200);	#存储过程名称
  DECLARE P_STATUS  	INT;  			#执行状态
  DECLARE P_START_DT  	DATETIME;		#日志开始日期
  DECLARE P_END_TIME  	DATETIME;		#日志结束日期
  DECLARE P_SQLCDE		VARCHAR(200);	#日志错误代码
  DECLARE P_STATE  		VARCHAR(200);	#日志状态代码
  DECLARE P_SQLMSG		VARCHAR(2000);	#日志详细信息
  DECLARE P_STEP_NO   	INT;			#日志执行步骤
  DECLARE P_DESCB  		VARCHAR(200);	#日志执行步骤描述
  DECLARE BEG_MON_DT 	VARCHAR(8);		#月初
  DECLARE BEG_QUAR_DT 	VARCHAR(8);		#季初
  DECLARE BEG_YEAR_DT 	VARCHAR(8);		#年初
  DECLARE LAST_MON_DT  	VARCHAR(8);		#上月末
  DECLARE LAST_QUAR_DT  VARCHAR(8);		#上季末
  DECLARE LAST_YEAR_DT  VARCHAR(8);		#上年末
  DECLARE LAST_DT  		VARCHAR(8);		#上日
  DECLARE FINISH_FLG    VARCHAR(8);		#完成标志  
  #声明异常
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
   GET DIAGNOSTICS CONDITION 1 P_SQLCDE = GBASE_ERRNO,P_SQLMSG = MESSAGE_TEXT,P_STATE = RETURNED_SQLSTATE;
   SET P_STATUS = -1;
   SET P_START_DT = NOW();
   SET P_STEP_NO = P_STEP_NO + 1;
   SET P_DESCB = '程序异常';
   CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
   SET OI_RETCODE = P_STATUS; 
   SET OI_REMESSAGE = P_DESCB || ':' || P_SQLCDE || ' - ' || P_SQLMSG;
   SELECT OI_RETCODE,'|',OI_REMESSAGE;
  END;
  
    #变量初始化
	SET P_DATE = TO_DATE(I_DATE,'YYYYMMDD');		
	SET BEG_MON_DT = SUBSTR(I_DATE,1,6) || '01';	
	SET BEG_QUAR_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY') || TRIM(TO_CHAR(QUARTER(TO_DATE(I_DATE,'YYYYMMDD')) * 3 - 2,'00')) || '01'; 
	SET BEG_YEAR_DT = SUBSTR(I_DATE,1,4) || '0101';	
    SET LAST_MON_DT = TO_CHAR(TO_DATE(BEG_MON_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_QUAR_DT = TO_CHAR(TO_DATE(BEG_QUAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
    SET LAST_YEAR_DT = TO_CHAR(TO_DATE(BEG_YEAR_DT,'YYYYMMDD') - 1,'YYYYMMDD');	
	SET LAST_DT = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD') - 1,'YYYYMMDD'); 			
	SET P_PROC_NAME = 'PROC_BSP_T_4_2_KMXX';
	SET OI_RETCODE = 0;
	SET P_STATUS = 0;
	SET P_STEP_NO = 0;
	
    #1.过程开始执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程开始执行';
				 
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);								

    #2.清除数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '清除数据';
	
	DELETE FROM T_4_2 WHERE D020011 = TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD');
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);								

	
	COMMIT;
   														
    
    #3插入数据
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '数据插入';
	
   INSERT  INTO T_4_2  (
       D020001  , -- 01 科目ID
       D020002  , -- 02 机构ID
       D020003  , -- 03 科目名称
       D020004  , -- 04 科目级次
       D020005  , -- 05 科目类型
       D020006  , -- 06 借贷标识
       D020007  , -- 07 归属业务子类
       D020008  , -- 08 上级科目ID
       D020009  , -- 09 分户账标识
       D020010  , -- 10 备注
       D020011  , -- 11 采集日期
       DIS_DATA_DATE, -- 装入数据日期
	   DIS_BANK_ID ,   -- 机构号
       DIS_DEPT,
       DEPARTMENT_ID
       )
     SELECT 
         T1.STAT_SUB_NUM     , -- 01 科目ID
		 SUBSTR(TRIM(T2.FIN_LIN_NUM),1,11) || T1.ORG_NUM        , -- 02 机构ID
         REPLACE(T1.GL_CD_NAME,'、','.')       , -- 03 科目名称
         CASE
             WHEN T1.GL_CD_GRD = '1' THEN '01'
             WHEN T1.GL_CD_GRD = '2' THEN '02'
             WHEN T1.GL_CD_GRD = '3' THEN '03'
          END                , -- 04 科目级次
          CASE
             WHEN T1.GL_CD_TYPE = '1' THEN '01'
             WHEN T1.GL_CD_TYPE = '2' THEN '02'
             WHEN T1.GL_CD_TYPE = '3' THEN '03'
             WHEN T1.GL_CD_TYPE = '4' THEN '04'
             WHEN T1.GL_CD_TYPE = '5' THEN '05'
             WHEN to_number(SUBSTR(T1.STAT_SUB_NUM,1,1)) >= 7 THEN '06'  -- 20241227 增加科目第一位大于等于7，类型映射为表外  06 YBT_JYD02-32 
             WHEN T1.GL_CD_TYPE = '7' THEN '00'
          END                , -- 05 科目类型
          CASE
             WHEN T1.CD_TYPE = '1' THEN '01'
             WHEN T1.CD_TYPE = '2' THEN '02'
             WHEN T1.CD_TYPE = '3' THEN '03'
          END                , -- 06 借贷标识
          -- T4.GB_CODE, -- T1.GL_CD_SUB_TYPE   , -- 07 归属业务子类
		  
	     M.GB_CODE			,-- 07 归属业务子类 20240614 修改
		 CASE
             WHEN T1.GL_CD_GRD = '1' THEN
          NULL -- '0'
             ELSE
              T1.SUPER_ITEM_CD
           END                , -- 08 上级科目ID
         CASE WHEN T3.D030008 IS NOT NULL THEN '1'
         ELSE '0' END , -- T1.FHZBS             , -- 09 分户账标识
         NULL                 , -- 10 备注
         TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),  -- 11 采集日期 
         TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'),
         T1.ORG_NUM,
         '',
         '009806'
      FROM SMTMODS.L_FINA_INNER T1 -- 科目表
      INNER JOIN -- SMTMODS.L_PUBL_ORG_BRA T2
        ( SELECT * FROM SMTMODS.L_PUBL_ORG_BRA T1
            WHERE T1.DATA_DATE = I_DATE
              AND T1.ORG_NUM<>'999999' AND T1.ORG_NUM NOT LIKE '5%' AND T1.ORG_NUM NOT LIKE '6%' AND T1.ORG_NUM NOT LIKE '7%' AND  T1.ORG_NAM NOT  LIKE  '%村镇%' 
              AND T1.ORG_NUM NOT IN ('120000','120100','120101','021203','020206','021305','020212','021407','020214','021204','020204', '010312','010624','010625','010627','010911','012512')-- 集团不报
              AND T1.BUSI_STATE <> '04' ) T2  -- JLBA202411070004_20241212 与1.1一致
           ON T1.ORG_NUM = T2.ORG_NUM
          AND T2.DATA_DATE = I_DATE
      LEFT JOIN (
       SELECT T6.D030008,T6.D030015 FROM (
      SELECT  T5.D030008,T5.D030015,
      ROW_NUMBER()  OVER(PARTITION BY T5.D030008 ORDER BY T5.D030001 DESC) AS NR
     FROM T_4_3 T5 WHERE T5.D030015=TO_CHAR(TO_DATE(I_DATE,'YYYYMMDD'),'YYYY-MM-DD'))T6
      WHERE   NR = '1'
      ) T3 
      ON T1.STAT_SUB_NUM=T3.D030008
     /* LEFT JOIN M_DICT_CODETABLE M -- 码表
           ON T1.BUSI_SUB_TYPE2 = M.L_CODE
          AND M.L_CODE_TABLE_CODE = 'C0173' -- 归属业务子类2*/
      /*LEFT JOIN M_DICT_CODETABLE T4
      ON T1.STAT_SUB_NUM=T4.L_CODE
      AND T4.L_CODE_TABLE_CODE='C0015' AND T4.L_CODE NOT IN (SELECT L_CODE FROM M_DICT_CODETABLE T5 WHERE T5.L_CODE_TABLE_CODE='C0015'  GROUP BY T5.L_CODE HAVING COUNT(*)>1)*/
	  LEFT JOIN M_DICT_CODETABLE M
			ON T1.STAT_SUB_NUM = M.L_CODE
			AND  M.L_CODE_TABLE_CODE='C0003'  -- 20240614修改 归属业务子类3  20241227 20110211  转股协议存款 该科目归属业务子类   大为哥确认取消54 4001 实收资本   大为哥 实收资本映射  47 YBT_JYD02-25 YBT_JYD02-26
     WHERE T1.DATA_DATE = I_DATE
       AND T1.ORG_NUM <> '999999' AND T1.STAT_SUB_NUM NOT  LIKE '9%'
     ;
     
    
       COMMIT;

	   
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);		

    #4.过程结束执行
	SET P_START_DT = NOW();
	SET P_STEP_NO = P_STEP_NO + 1;
	SET P_DESCB = '过程结束执行';
	CALL PROC_ETL_JOB_LOG(P_DATE,P_PROC_NAME,P_STATUS,P_START_DT,NOW(),P_SQLCDE,P_STATE,P_SQLMSG,P_STEP_NO,P_DESCB);
   SET OI_RETCODE = P_STATUS; 
   SET OI_REMESSAGE = P_DESCB;
   SELECT OI_RETCODE,'|',OI_REMESSAGE;
END $$

